var zbllMap = {
    // For T cases
    "T": {
        // This is the 2GLL subset
        "2GLL": {
            "AsA": [
                "R B2 R2 U2 B2 R' B2 U2 R U' R2 U B2 U' R2",
                "R' D2 F2 L' F2 D2 R2 B2 R' U' R2 U B2 U' R2",
                "R' D2 F2 R' D2 B2 R2 U2 L' U' R2 U B2 U' R2",
                "R B2 R2 U2 B2 R' B2 U2 R U' R2 U B2 U' R2",
                "R' D2 F2 L' F2 D2 R2 B2 R' U' R2 U B2 U' R2",
                "R' D2 F2 R' D2 B2 R2 U2 L' U' R2 U B2 U' R2",
                "F' U' F U2 R2 B2 U B' D B D' B U' B2 R2",
                "F' R2 D' L2 D2 B' D' R2 D' L2 D F' U F2",
                "F2 L2 F' R' F L2 D2 B' L B D2 F2 R",
                "F' R2 D' L2 D2 B' D' R2 D' L2 D F' U F2",
                "B U' F U2 L U' L' F' B' U2 L' U L",
                "D R2 U' R2 B R U2 R2 U' R B' U R2 D' U2 R'",
                "F L2 U L2 F L2 B' U' F2 U' F B U' F L2 F'",
                "R' U' R D' F2 D U2 R D' R' F2 R2 U R' D R'",
                "R2 U' B2 U B D' R2 U F B' U' B D F U F'",
                "F' B' U2 F2 B R' B D2 F B' R F2 U2 B L B'",
                "F' U R U R D R' U' R D B' L2 D' B D' R2",
                "D' B U2 B' D L U' L' D' B U' B' D L U2 L'",
                "B U2 B' D L U' L' D' B U' B' D L U2 L' D'",
                "R' U R2 U2 R2 U' R L2 D2 R' D2 L2 U2 R U R'",
                "B2 R B U2 R' U B2 U2 R U' B2 U B' R' U2 B'",
                "F2 U2 F' D U R U R2 D' F D R' U R2 D' F",
                "L U R L' U R2 D' F2 L2 D L U L' U' F2 R",
                "B' R' U R U B2 D2 L' U L D' L2 U' L D' B'",
                "R' U2 B' R F2 U2 F' R F' R F' B' R2 F B2 R",
                "R2 B' R B2 U2 B' R U2 F D U R2 D' U' R F'",
                "F2 D' L2 U L' U2 L U' L2 D F2 D' L U' L' D",
                "R B L' B' R' B2 R' D2 R B' L2 F L F2 L2 B'",
                "F R2 B2 R' B' R F L' F' R F D2 L F' R F'",
                "L U2 L2 B2 L2 B' U' B' R' L F U F' L2 U2 R",
                "B' U2 F U' B D2 U' F' U' B' U2 F U B D2 F'",
            ],
            "OsC": [
                "R U' L2 U B L2 B' R' F U2 F' U' L2",
                "D L D' F2 L2 U' L2 D F2 L' D' F2 U F2",
                "D' F' U2 F' U2 F D R2 D' F U F' D R2",
                "D' B' R2 F' R2 B D R2 D' F U F' D R2",
                "F D B' D B2 D F D' B L2 D' B2 D' F2",
                "F2 U' L2 B2 R D L B2 R2 U' L U' R F2",
                "F' U2 F' U2 F D R2 D' F U F' D R2 D'",
                "B U' F2 U L F2 L' B' R U2 R' U' F2",
                "B' R2 F' R2 B D R2 D' F U F' D R2 D'",
                "L D' F2 L2 U' L2 D F2 L' U' R2 U R2",
                "L D' F2 L2 U' L2 D F2 L' D' F2 U F2 D",
                "L2 D' B2 D L' U2 L D' B2 D L' U2 L'"
            ],
            "OxC": [
                "L D F2 D' L2 U L' D R' D R' D' R2 D' L2",
                "L2 B D' L2 F L2 B D' B2 L2 U' F' U' F2",
                "R' U' R U2 B2 L U' L' U L U L' B2",
                "F' U' F U2 R2 B U' B' U B U B' R2",
                "F' L F2 L' U' F2 U F2 U R U2 R' F",
                "F' L F2 L' D' L2 U L2 D R U2 R' F",
                "L' U' B' U' B U' L F' L F L2 U' L",
                "L' U' B' U' B2 L2 D L D' L B' U2 L",
                "R' U' F' U L' U L U' L F' L' F2 R",
                "R' U' R U2 B2 L U' L' U L U L' B2",
                "L' D2 F2 L' U2 R2 L D U B2 R' U R' D L'",
                "R' D2 F2 D R2 U L' U' L U' R2 D' F2 D2 R",
                "R' F2 L D' L D' B' R2 B D2 L2 F' U2 F' R",
                "R2 D2 U R' D2 R D2 B2 R B2 U' L' D2 R2 L",
                "L' U2 L2 F2 D R' F2 U' R U R F2 D' L' F2",
                "R' F2 L D' L D' F' U2 B R2 D2 B' U2 F' R",
                "R' U L2 D F2 D2 L' U' L D2 F2 D' L2 U' R",
                "B2 D F2 D' R2 F' L2 F R2 B' D U2 F2 D' B'",
                "B2 D F2 D R2 F D2 B' L2 D2 F' D' F2 D' B'",
                "R' U' R U2 B U2 R' U' R U R B' R' B U' B'",
                "R' U' R U' R U2 R2 U2 R' B' R2 B U F' U F",
                "R' D' F U' F U F' U F U2 F' U2 F' D U R",
                "R' U R U' R U2 R B R B' R B R2 B' U2 R'",
                "R U2 R' U' R U' R' L U2 L2 U' L2 U' L2 U2 L",
                "F U F' U F U2 F' R U2 R2 U' R2 U' R2 U2 R",
                "L U2 L2 U' L2 U' L2 U2 L B U B' U B U2 B'",
                "B U2 B R' B2 R B R' B R U2 B' U' B' U B",
                "F R U' R' U2 F' U' L U2 L2 U' L2 U' L2 U L",
                "R' U' F' U F U' F R' F D' F' D F' R U R",
                "L' U L F U' F' U2 L' U' L F' L F L2 U' L",
                "R' U' R U' R U2 R2 D' F2 U' F2 D R"
            ],
            "CsO": [
                "B D' B2 U2 R2 F' U' F R2 B U2 B2 D B2",
                "B L2 B2 D' R2 D B2 U' L2 B D F2 D' B2",
                "L U F2 U2 F2 L2 D' L' B2 U B2 U' L2 D",
                "L2 B U' B2 D F2 L2 D' L2 B D F2 D' L2",
                "D B U L2 U2 L2 B2 D' B' R2 U R2 U' B2",
                "D B' D B D2 F2 R2 U2 F' U' F U2 R2 U' F2",
                "F U2 F' U' R2 U' B U F U' F' B' U R2",
                "F U' B U2 F U F2 D' L2 D L2 B L2 B2",
                "F L' B2 R2 B' D B D' R2 B2 L F'",
                "B R' F2 L2 F' D F D' L2 F2 R B'",
                "F L' B2 R2 B' D B D' R2 B2 L F'",
                "L' B2 R2 B' D B D' R2 B2 L F' U2 F"
            ],
            "CsC": [
                "L' U B2 U' B2 U' L' U L2 D' B2 D B2",
                "L' D L2 U' L2 D' L' U L2 D' B2 D B2",
                "R U' B2 U B2 U R U' R2 D B2 D' B2",
                "R D' R2 U R2 D R U' R2 D B2 D' B2",
                "R2 U' F2 U R' B2 R U' F2 U R' B2 R'",
                "R2 F' R U2 F' U2 F R2 B' R F R2 B",
                "R2 B' D R2 F' R2 F D2 B' D B R2 B",
                "R2 B' D2 F D' F' R2 F' R2 F D' R2 B",
                "R2 B' D2 F D' B' D2 F' D2 B D' R2 B",
                "R' U2 R' B D2 B' R U2 R' B D2 B' R2",
                "R' D R2 U' B2 U B2 R' U R2 D' R2",
                "R' D R2 U' B2 U B2 R' D B2 D' B2 D'"
            ],
            "CsA": [
                "D' B D' B' D2 F2 L2 U2 F U F' U2 L2 U F2",
                "D' B' U' R2 U2 R2 B2 D B L2 U' L2 U B2",
                "F U B' U2 F' U' F2 D R2 D' R2 B' R2 F2 B2",
                "F U2 F' D F2 U L F' U F U' L' U' F2 D'",
                "F U2 F' D F2 U2 B U' F' U F B' U2 F2 D'",
                "F U2 F' D' F2 U2 B' U' F' U F B U2 F2 D",
                "F R B2 L2 B D' B' D L2 B2 R' F U2 F2",
                "F' U B' U2 F' U' F2 D R2 D' R2 B' R2 B2",
                "F' R B2 L2 B D' B' D L2 B2 R' F",
                "B' L F2 R2 F D' F' D R2 F2 L' B",
                "F' R B2 L2 B D' B' D L2 B2 R' F",
                "R B2 L2 B D' B' D L2 B2 R' F U2 F'"
            ],
            "OsA": [
                "R' D F2 R2 U R2 D' F2 R D F2 U' F2 D'",
                "B' D R2 B2 U B2 D' R2 B U F2 U' F2",
                "L' U R2 U' B' R2 B L F' U2 F U R2",
                "D F U2 F U2 F' D' L2 D F' U' F D' L2",
                "D B L2 F L2 B' D' L2 D F' U' F D' L2",
                "D' R' D F2 R2 U R2 D' F2 R D F2 U' F2",
                "F U2 F U2 F' D' L2 D F' U' F D' L2 D",
                "F2 U R2 B2 L' D' R' B2 L2 U R' U L' F2",
                "F' D' B D' B2 D' F' D B' R2 D B2 D F2",
                "B L2 F L2 B' D' L2 D F' U' F D' L2 D",
                "B' U F2 U' R' F2 R B L' U2 L U F2",
                "R2 D B2 D' R U2 R' D B2 D' R U2 R"
            ],
            "CxO": [
                "B U B' D L2 D2 R2 F D' F U' F2 L2 D2 R2",
                "B2 R' U2 L2 U L2 U L2 U R U L2 U' B2",
                "B' D B' U B2 L2 D2 R2 F' U' F D' L2 D2 R2",
                "L U' B2 D2 R U D F2 U2 D R' U R2 B2",
                "R2 F' U2 B2 U B2 U B2 U F U B2 U' R2",
                "R U' F2 D2 L U D B2 U2 D L' U L2 F2",
                "F2 U F2 D' F' U2 F' D F U2 F' R2 U' R2 F2",
                "B U B' D L2 D2 R2 F D' F U' F2 L2 D2 R2",
                "B2 L2 U L2 B U' B D' L2 F' D F L2 U D",
                "B2 R' U2 L2 U L2 U L2 U R U L2 U' B2",
                "B' U2 B2 L' B' L B' U R' U R B",
                "B' U' R B' D B' D' B2 R2 U R B"
            ],
            "AsC": [
                "B2 L U2 R2 U' R2 U' R2 U' L' U' R2 U B2",
                "L2 B' L' F R2 F' L B' U F2 D F2 U' B2 L2",
                "L2 B' L' F R2 F' L B' D R2 D R2 D' B2 L2",
                "R' U B2 D2 L' U' D' F2 U2 D' L U' L2 B2",
                "F' U R2 D2 B' U' D' L2 U2 D' B U' B2 R2",
                "F2 R U2 L2 U' L2 U' L2 U' R' U' L2 U F2",
                "B U L' B D' B D B2 L2 U' L' B'",
                "B U2 B2 R B R' B U' L U' L' B'",
                "L U F' L D' L D L2 F2 U' F' L'",
                "L U2 L2 B L B' L U' F U' F' L'",
                "B U L' B D' B D B2 L2 U' L' B'",
                "B U2 B2 R B R' B U' L U' L' B'"
            ],
            "OsO": [
                "B' D B' U L2 D2 R2 F U' F D' L2 D2 R2",
                "L' B R' B D2 L2 U2 R F' L F' R2 D2 L2",
                "R B' L B' D2 R2 U2 L' F R' F L2 D2 R2",
                "B D' B U' R2 D2 L2 F' U F' D R2 D2 L2",
                "B' D B' U L2 D2 R2 F U' F D' L2 D2 R2",
                "L F' L' F U2 L' B' R B L' B2 R' B2 L2",
                "L2 F2 L B L' F2 L2 F' L' B' L F",
                "R2 F2 R' B' R F2 R2 F R B R' F'",
                "L2 B2 L' F' L B2 L2 B L F L' B'",
                "R2 B2 R F R' B2 R2 B' R' F' R B",
                "L2 F2 L B L' F2 L2 F' L' B' L F",
                "R2 F2 R' B' R F2 R2 F R B R' F'"
            ],
            "AsO": [
                "F B' U B L2 D F D' L2 U F' L2 U L2 U' L2",
                "F2 U F' D F2 U' R2 U' D2 L2 B' D L2 D R2 D'",
                "L' D L' U L2 D2 B2 U' R' U2 R' U R2 D B2",
                "R' U2 R2 U' L U' R2 U' R' U L' U' B2 R2 B2",
                "R' D' F2 D R2 U' R D' L D' L D L2 D R2",
                "L U L' U2 B2 R' U R U' R' U' R B2",
                "F U F' U2 L2 B' U B U' B' U' B L2",
                "F R' F2 R U F2 U' F2 U' L' U2 L F'",
                "F R' F2 R D R2 U' R2 D' L' U2 L F'",
                "L U F U' R U' R' U R' F R F2 L'",
                "R D2 F2 R U2 R' L2 D' U' B2 L U' L D' R",
                "L F2 R' D R' D B L2 B' D2 R2 F U2 F L'",
                "L2 D2 U' L D2 L' D2 B2 L' B2 U R D2 R' L2",
                "R U2 R2 F2 D' L F2 U L' U' L' F2 D R F2",
                "L F2 R' D R' D F U2 B' L2 D2 B U2 F L'",
                "L U' R2 D' F2 D2 R U R' D2 F2 D R2 U L'",
                "B2 D' F2 D L2 F R2 F' L2 B D' U2 F2 D B",
                "B2 D' F2 D' L2 F' D2 B R2 D2 F D F2 D B",
                "L U L' U2 B' U2 L U L' U' L' B L B' U B",
                "L U L' U L' U2 L2 U2 L B L2 B' U' F U' F'",
                "L D F' U F' U' F U' F' U2 F U2 F D' U' L'",
                "L U' L' U L' U2 L' B' L' B L' B' L2 B U2 L",
                "L' U2 L U L' U R' L U2 R2 U R2 U R2 U2 R'",
                "F' U' F U' F' U2 F L' U2 L2 U L2 U L2 U2 L'",
                "R' U2 R2 U R2 U R2 U2 R' B' U' B U' B' U2 B",
                "F' L' U L U2 F U R' U2 R2 U R2 U R2 U' R'",
                "B' U2 B' L B2 L' B' L B' L' U2 B U B U' B'",
                "L U F U' F' U F' L F' D F D' F L' U' L'",
                "R U' R' F' U F U2 R U R' F R' F' R2 U R'",
                "L F' L2 F L2 U' L' U L' U' L' U F' L2 F L'",
                "L U L' F' U2 F2 U F2 U F2 U2 F' U L U L'",
                "L U L' U2 B' U F U F' U' F' L F L' U2 B",
                "L U L' U2 B' U' B U' F' L2 F L' U' L2 U L",
                "L U L' U L' U2 L2 D F2 U F2 D' L'"
            ],
            "OxO": [
                "L D2 F2 L D2 B2 L2 U2 R U L2 U' B2 U L2",
                "L D2 F2 R F2 D2 L2 B2 L U L2 U' B2 U L2",
                "L' B2 L2 U2 B2 L B2 U2 L' U L2 U' B2 U L2",
                "L D2 F2 L D2 B2 L2 U2 R U L2 U' B2 U L2",
                "L D2 F2 R F2 D2 L2 B2 L U L2 U' B2 U L2",
                "L' B2 L2 U2 B2 L B2 U2 L' U L2 U' B2 U L2",
                "F U F' U2 L2 B2 U' B D' B' D B' U B2 L2",
                "F L2 D R2 D2 B D L2 D R2 D' F U' F2",
                "F2 R2 F L F' R2 D2 B R' B' D2 F2 L'",
                "B' U F' U2 R' U R F B U2 R U' R'",
                "F B U2 F2 B' L F U2 B2 R F' B D2 F R' B",
                "R F' R U R2 F' U2 B' R B R2 F2 R U F2 R2",
                "B U2 F2 D' L' B2 L B L' B L B D F2 U2 B'",
                "L' U2 L' B' L2 B L' D2 F D2 L D2 F' D2 U2 L",
                "L' U2 B L' D2 B' L' F2 R' F' L' F' R B' R' B",
                "R2 F R F' R F2 B D2 F' R B R' F D2 F2 B'",
                "R' U2 B R2 B L F' U2 F' L' B2 R L F2 R L'",
                "L2 B2 R B D B R2 L' F2 L2 U L F' U' F' R",
                "F' B D2 F2 D L2 D' F2 D2 B' U2 F U2 F2 U' F'",
                "B' U2 F' D2 B D B2 D F U' L2 F U' B U F'",
                "R2 U' R2 D2 F' D' B2 D F D2 U B2 U B2 U' B2",
                "L' D L2 F2 U F2 L2 D' B2 L2 U' L' U R' U R",
                "D2 B L2 B' D F' U2 F2 U' F' U F2 D B' R2 B",
                "B L2 B' D F' U2 F2 U' F' U F2 D B' R2 B D2",
                "F' D F2 D2 B L2 B' D2 F2 D' U2 F U2 F2 U' F'",
                "L' U B2 D L' U' L2 D' R' L U2 R U' B2 L2 B2",
                "R' U2 R L' D L2 U L D' B2 U' L U B2 L2 B2",
                "B2 D L2 F B D' B U R2 U2 B D U' F' D' B'",
                "R' U2 R' L U R2 U L D' F2 D' R2 L D2 R L",
                "R' U F2 U2 F2 U2 F2 R U2 B2 L2 U L U' L2 B2",
                "R2 F2 B2 L F U2 F L' B' R2 B' U2 L' U2 R L",
            ],
        },

        "Diag": {
            "AsO": [
                "L U' D L' U2 L D' L U L' U2 L U L2",
                "L D R U' R U D' F2 L D2 R' D2 L2",
                "R D L U' L U D' B2 R D2 L' D2 R2",
                "B2 D2 F' D2 B R2 U D' F U' F D B",
                "L U' D L' U2 L D' L U L' U2 L U L2",
                "L D R U' R U D' F2 L D2 R' D2 L2",
                "F2 D2 B' D2 F L2 U D' B U' B D F",
                "R D L U' L U D' B2 R D2 L' D2 R2",
                "F2 U F U2 F' U F D' F U2 F' U' D F",
                "B2 D2 F' D2 B R2 U D' F U' F D B",
                "L U' D L' U2 L D' L U L' U2 L U L2",
                "L D R U' R U D' F2 L D2 R' D2 L2"
            ],
            "OsO": [
                "R2 L' U R U' R' L U' R U2 R' U2 R2",
                "B U B2 U F' U B2 U' F U2 B2 U B",
                "L2 U' L D L' U' L D' L U L2 U L2",
                "B U B2 U F U' R2 U' R2 U B R2 F'",
                "L2 U' F U' F' U' B U L2 U' B' U2 L2",
                "R U' B U B2 D' F R2 F' D B U' R'",
                "L2 D' B D B' U' B D' B U B2 D L2",
                "B U B2 U F D' F2 U' F2 D B R2 F'",
                "R2 D R D' F2 R U2 L F2 L2 U' L F2",
                "F' U2 F U F' U' B U' B' U2 F B U' B'",
                "R U' L' U R' U2 B' U2 B U' B' U' B L",
                "B' U2 L' U R' U' L U' R U' R' U' R B",
                "F' U2 F U F' U' B U' F U F' B' U2 F",
                "F' U2 F U F' R U2 F U F' U R' U F",
                "R' L' U R U' B2 U' B2 U B2 R' L U R",
                "R U' L' U R' U2 B' U2 B U L F U' F'",
                "F' U L U' R U' L' U R' U2 F L U' L'",
                "B' U' B2 L' B' L2 U L' B L' B' L2 U2 L'",
                "B' U2 L' U R' U' L U' R U B L U' L'",
                "R B' U R' U' R B R' F' U2 F L U' L'",
                "R2 L' U R U' R' L U' L F2 R' F2 R' L'",
                "F L F' L2 U2 L2 U L2 U L2 U2 F L' F'",
                "R' U B' U F U' R2 U' R2 U R2 F' B R",
            ],
            "AsA": [
                "R' U D' R U2 R' D R' U' R U2 R' U' R2",
                "R' D' L' U L' U' D F2 R' D2 L D2 R2",
                "L' D' R' U R' U' D B2 L' D2 R D2 L2",
                "B2 D2 F D2 B' L2 U' D F' U F' D' B'",
                "R' U D' R U2 R' D R' U' R U2 R' U' R2",
                "R' D' L' U L' U' D F2 R' D2 L D2 R2",
                "F2 D2 B D2 F' R2 U' D B' U B' D' F'",
                "L' D' R' U R' U' D B2 L' D2 R D2 L2",
                "F2 U' F' U2 F U' F' D F' U2 F U D' F'",
                "B2 D2 F D2 B' L2 U' D F' U F' D' B'",
                "R' U D' R U2 R' D R' U' R U2 R' U' R2",
                "R' D' L' U L' U' D F2 R' D2 L D2 R2"
            ],
            "OxO": [
                "L2 D' R2 D' L' U' R2 U L D R2 D' R2 D2 L2",
                "F2 U2 F' L2 U' F U' R2 D B D' R2 F2 U' L2",
                "F2 U2 R' U' F2 U R U' L' U' L U' F2",
                "L2 U L2 U L D' L U' L' D L U' L2",
                "L2 D F2 U F D' F U' F' D F D' L2",
                "F2 U' F U L' U2 F' U2 F L U' F",
                "L2 U L2 U L D' L U' L' D L U' L2",
                "L2 D F2 U F D' F U' F' D F D' L2",
                "R2 U' R U F' U2 R' U2 R F U' R",
                "F2 U' F U L' U2 F' U2 F L U' F",
                "L2 U L2 U L D' L U' L' D L U' L2",
                "L2 D F2 U F D' F U' F' D F D' L2"
            ],
            "OsA": [
                "L2 D B U' F2 U B U2 B2 D2 F2 L2 D F2 U' F2",
                "L' D F2 R U R' F2 L2 U' L U D' B2 U B2",
                "L' D F2 R U R' F2 L2 U' L' U L2 D'",
                "D' L' D F2 R U R' F2 L2 U' L' U L2",
                "L' D F2 R U R' F2 L2 U' L' U L2 D'",
                "D' L' D F2 R U R' F2 L2 U' L' U L2",
                "B2 U B' U' B2 R2 F' U F R2 D B' D'",
                "L' D F2 R U R' F2 L2 U' L' U L2 D'",
                "D' B2 U B' U' B2 R2 F' U F R2 D B'",
                "D' L' D F2 R U R' F2 L2 U' L' U L2",
                "B2 U B' U' B2 R2 F' U F R2 D B' D'",
                "L' D F2 R U R' F2 L2 U' L' U L2 D'"
            ],
            "CsO": [
                "D L U2 B L' B' D' U2 F' D L' D' F",
                "L D U2 F2 U' L F2 L' U F2 D' U2 L'",
                "R2 F2 R U' B L F2 L' B' U R' F2 R2",
                "B2 L2 D L' B' R' F2 R B L D' L2 B2",
                "B2 L2 U B' R' F' L2 F R B U' L2 B2",
                "B2 L2 U' R F L B2 L' F' R' U L2 B2",
                "L2 B2 R' D B' L' F2 L B D' R B2 L2",
                "B2 L2 D' F L B R2 B' L' F' D L2 B2",
                "L' U2 R U' R' U2 R L U R' U' R U' R'",
                "R U R' U R U' R' L' U2 R U R' U2 L",
                "L U' R U2 R' U L' U2 R U' R' L U L'",
                "L U' R L' U R' U2 L U' R U2 R' U L'",
                "R U R' U R U' R2 F R F2 L' U L F",
                "F' L' U' L F2 R' F' R2 U R' U' R U' R'",
                "R U R' U L' U2 R L U L' U R' U2 L",
                "L' U2 R U' L U' R' L' U2 L U' R U' R'",
                "F2 L' F' U F L F2 U' R U2 R' F U' F'",
                "R U R' B U2 B' U R2 F' R' U' R F R2",
                "F B' R' B R' F' R2 F' R' U2 R F U2 R'",
                "F U2 L' F' U2 F L F2 L F R' F R L'",
            ],
            "CxO": [
                "B2 L2 B' U F' D' B2 D F U' B' L2 B2 L2",
                "B2 R2 F' D B' U' F2 U B D' F' R2 B2 L2",
                "B2 R2 B U' F D B2 D' F' U B R2 B2 R2",
                "L' F' L' B L F L U L2 U' B' U L2",
                "R F R B' R' F' R' U' R2 U B U' R2",
                "F R F' U' L' U L2 F R' F' L2 U' L",
                "F2 U' L U F2 U' F' R' F' L' F R F",
                "B U' F' U B2 U F U' B U F' U2 F",
                "B U' B2 R' F' R B2 U B' U' R' F R",
                "R U2 R' U L U' R U L2 U R' U' L",
                "R F R B' R' F' R' U' R2 U B U' R2"
            ],
            "CsC": [
                "B2 U' B U B2 L2 F U' F' L2 D' B D",
                "D R D' F2 L' U' L F2 R2 U R U' R2",
                "R D' F2 L' U' L F2 R2 U R U' R2 D",
                "D B2 U' B U B2 L2 F U' F' L2 D' B",
                "R' U2 R2 B2 D B2 R' U R B2 D' B2 R'",
                "F' L2 D' L2 F U F' L2 D L2 F2 U2 F'",
                "F' B L2 B' L B L D L2 D' F L' B' L",
                "L F' L' B D' L2 D L F L F' L2 F B'",
                "F' U2 F B' R' F R D R2 D' B R' F' R",
                "L F' L' B D' L2 D L F L' F B' U2 F'",
                "R D' L U2 R U' R U R' U2 L' D B2 R'",
                "B' R2 D F' U2 B' U B U' B U2 F D' B",
                "L2 U R' D R U R U R2 D' L F2 R L",
                "F L2 F B2 U' L2 U L2 U B U2 F2 U' B",
                "F B L2 F D' B2 U B U B D B' U F2",
                "R B2 U' R D2 L D' L D L' D2 R' U R'",
                "B' U B' D2 F' D F D' F D2 B U' R2 B",
                "B U' F2 U2 B U R2 U R2 U' F B2 R2 F",
                "B U' F2 U2 B D B2 U B2 D' F B2 R2 F",
                "F L2 F B2 D' B2 U B2 D B U2 F2 U' B",
            ],
            "OsC": [
                "L2 F2 L' U B' R' F2 R B U' L F2 L2",
                "B2 R2 D' R B L F2 L' B' R' D R2 B2",
                "B2 R2 U L' F' R' B2 R F L U' R2 B2",
                "B2 R2 U' B L F R2 F' L' B' U R2 B2",
                "R2 B2 L D' B R F2 R' B' D L' B2 R2",
                "B2 R2 D F' R' B' L2 B R F D' R2 B2",
                "L' U' L U' L' U R L U2 L' U' L U2 R'",
                "R U2 L' U L U2 R' L' U' L U L' U L",
                "R' U L' U2 L U' R U2 L' U R' L U' R",
                "R' U R L' U' L U2 R' U L' U2 L U' R",
                "L' U' L U' L' U L2 F' L' F2 R U' R' F'",
                "F R U R' F2 L F L2 U' L U L' U L",
                "L' U' L U' R U2 R' L' U' R U' L U2 R'",
                "R U2 L' U R' U R L U2 R' U L' U L",
                "F2 R F U' F' R' F2 U L' U2 L F' U F",
                "L' U' L B' U2 B U' L2 F L U L' F' L2",
                "F' B L B' L F L2 F L U2 L' F' U2 L",
                "F' U2 R F U2 F' R' F2 R' F' L F' R L'",
                "B L2 U' F U' F' U B L2 B2 U F U F'",
            ],
            "AsC": [
                "F U R' D' L F2 L' D F D R' D' R2 F2",
                "F2 U2 F R2 U F' U L2 D' B' D L2 F2 U R2",
                "F2 U2 L U F2 U' L' U R U R' U F2",
                "R2 U' R2 U' R' D R' U R D' R' U R2",
                "R2 D' F2 U' F' D F' U F D' F' D R2",
                "F2 U F' U' R U2 F U2 F' R' U F'",
                "R2 U' R2 U' R' D R' U R D' R' U R2",
                "R2 D' F2 U' F' D F' U F D' F' D R2",
                "L2 U L' U' F U2 L U2 L' F' U L'",
                "F2 U F' U' R U2 F U2 F' R' U F'",
                "R2 U' R2 U' R' D R' U R D' R' U R2",
                "R2 D' F2 U' F' D F' U F D' F' D R2"
            ],
            "OxC": [
                "F L U' B' D R2 D' B U2 F2 U' F2 L' U F'",
                "F R F B U F' U B' U' L' R' U2 L U2 F'",
                "F' U2 F' U2 F2 U F L F U F U' F' L' F2",
                "F' R2 U R2 F' R2 U2 L2 D B R2 D' L2 U2 F'",
                "B' R2 D2 F2 D F R F D R2 B R' F' U F",
                "B' R2 D2 F2 D F R2 F R2 D B R2 F' U F",
                "R U R' F2 L D F2 R F2 R D R2 D2 F2 L'",
                "R U R' F' L F2 D R F R D R2 D2 F2 L'",
                "R2 B' R' U' R U R B R U R2 U2 R' U2 R'",
                "R' U B' R2 U' R2 U2 L D' F2 D L' U' B R",
                "R' U2 B U2 F' B' U' L' U R' U L R F R",
                "R' U2 B2 D' F2 L D B2 U2 F2 R' F2 U F2 R'"
            ],
            "CsA": [
                "F B2 U' B' U F' B U B' U2 B U2 B2",
                "R' U' R2 U' L U' R2 U L' U2 R2 U' R'",
                "F2 U F' D' F U F' D F' U' F2 U' F2",
                "R' U' R2 U' L' U B2 U B2 U' R' B2 L",
                "F2 U L' U L U R' U' F2 U R U2 F2",
                "B' U R' U' R2 D L' B2 L D' R' U B",
                "F2 D R' D' R U R' D R' U' R2 D' F2",
                "R' U' R2 U' L' D L2 U L2 D' R' B2 L",
                "B2 D' B' D L2 B' U2 F' L2 F2 U F' L2",
                "L U2 L' U' L U R' U R U2 L' R' U R",
                "B' U F U' B U2 R U2 R' U R U R' F'",
                "R U2 F U' B U F' U B' U B U B' R'",
                "L U2 L' U' L U R' U L' U' L R U2 L'",
                "L U2 L' U' L B' U2 L' U' L U' B U' L'",
                "F B U' B' U R2 U R2 U' R2 F' B U' B'",
                "B' U F U' B U2 R U2 R' U' F' L' U L",
                "L U' F' U B' U F U' B U2 L' F' U F",
                "R U R2 F R F2 U' F R' F R F2 U2 F",
                "R U2 F U' B U F' U B' U' R' F' U F",
                "F B2 U' B' U F' B U F' L2 B L2 F B",
            ],
        },

        "3": {
            "AsA": [
                "L U L D L' U' L F2 U' R2 U R2 D' F2 L2",
                "L U L D L' U' L F2 D' F2 U F2 U' F2 L2",
                "F2 B U' F U F B' U F' U2 F U F2 U F2",
                "B U2 R' U2 R U' B' U L' B' L U B2 U' B2",
                "L' U' L F R F U2 F' U' R' F' U F2 U2 F2",
                "L' U' L' D' L' D L' D' L' U L D F2 U' F2",
                "D' B' U' B L F L U2 L' U' F' L' D F2 U2 F2",
                "D' L2 R U' L U L R' U L' U2 L D F2 U F2",
                "D' R U2 F' U2 F U' R' U B' R' B D B2 U' B2",
                "F2 B' U' B U' L2 F' L2 U' F' U F U2 F2",
                "F' U2 F U F2 U B U' F U F B'",
                "B' U' B U' L2 F' L2 F U F U' F'"
            ],
            "AsC": [
                "B' U2 L U2 L' U B U' R B R' U' B2 U B2",
                "R U R D R D' R D R U' R' D' F2 U F2",
                "R U R' F' L' F' U2 F U L F U' F2 U2 F2",
                "R' U' R' D' R U R' F2 U L2 U' L2 D F2 R2",
                "R' U' R' D' R U R' F2 D F2 U' F2 U F2 R2",
                "D B U B' R' F' R' U2 R U F R D' F2 U2 F2",
                "D L' U2 F U2 F' U L U' B L B' D' B2 U B2",
                "D L' R2 U R' U' L R' U' R U2 R' D' F2 U' F2",
                "F U2 F' U' F U' F B U' F2 U B' U' F2 U F2",
                "F U2 F' U' F U' F' B' D' F2 D B' D' F2 D B2",
                "F U2 F' U' F2 U' B' U F' U' F' B",
                "B U B' U R2 F R2 F' U' F' U F"
            ],
            "OsA": [
                "F2 B D' B D' R2 B' D2 B D F D' F B2",
                "B2 U L2 U L2 U2 B U F U2 B U' F' U' L2",
                "L' U' L U' F U' F U R' F R F' U' F2",
                "L' U' L U' F U' F R B U' B' U R' F2",
                "L2 R D' R D' F2 R' D2 R D L D' L R2",
                "R' U' R U' B U' B U L' B L B' U' B2",
                "R' U' R U' B U' B L F U' F' U L' B2",
                "F L' B D L' F' L' F2 L D' L2 B' U2 F'",
                "F2 L' U' L2 F' L' U F U' R' F2 R U' F",
                "F2 L' U' L2 F' L' F2 R' D' F D R U' F",
                "L' U' B' U2 R' U R U' R' U' R U' B L",
                "L' B L' B' L' D R F R' D' F L' U2 F'"
            ],
            "CsA": [
                "B U B D B' U' B D2 R2 U F2 U' F2 D R2 B2",
                "B U B D B' U' B D2 R2 D R2 U' R2 U R2 B2",
                "B' D R2 B' D L2 U' F D' F2 U2 B2 R2 D F2",
                "L F2 R U' R' U F2 L' F2 U F2 U' F2 U' F2",
                "L F2 R U' R' U F2 L' F2 D R2 U' R2 D' F2",
                "L F2 R U' R' U F2 L' F2 U F2 U' F2 U' F2",
                "L F2 R U' R' U F2 L' F2 D R2 U' R2 D' F2",
                "L' F2 D2 R U' R' U' B2 R U R2 D B2 D F2",
                "B D L B' U2 B' U' B U2 L' U' B2 D' B2",
                "B' U L2 D2 F' U' R2 U2 D' F U' F2 D' L2",
            ],
            "CsC": [
                "B' U' B' D' B U B' D2 L2 D' L2 U L2 U' L2 B2",
                "B D' L2 B D' R2 U F' D F2 U2 B2 L2 D' F2",
                "R' F2 L' U L U' F2 R F2 U' F2 U F2 U F2",
                "R' F2 L' U L U' F2 R F2 D' L2 U L2 D F2",
                "R F2 D2 L' U L U B2 L' U' L2 D' B2 D' F2",
                "R' F2 L' U L U' F2 R F2 U' F2 U F2 U F2",
                "R' F2 L' U L U' F2 R F2 D' L2 U L2 D F2",
                "B U' R2 D2 F U L2 U2 D F' U F2 D R2",
                "B' D' R' B U2 B U B' U2 R U B2 D B2",
                "R F2 D2 L' U L U B2 L' U' L2 D' B2 D' F2",
            ],
            "CsO": [
                "F U' R2 U2 R2 U2 R2 F' U L2 D' B D L2",
                "F' U L2 U2 L2 U2 L2 F U' R2 D B' D' R2",
                "F' U R2 D2 L2 D2 R2 F U' R2 D B' D' R2",
                "F' U2 F2 U D R2 D' F' U L2 D' B D L2",
                "B U B L' D2 R F' R' D2 L2 B' L' U' B'",
                "B U L B L2 D2 R F R' D2 L B' U' B'",
                "B D F L F2 D2 B R B' D2 F L' D' B'",
                "B D L F' D2 B R' B' D2 F2 L' F' D' B'",
                "B' U' B' R D2 L' F L D2 R2 B R U B",
                "B' U' R' B' R2 D2 L' F' L D2 R' B U B",
                "B' D' F' R' F2 D2 B' L' B D2 F' R D B",
                "B' D' R' F D2 B' L B D2 F2 R F D B"
            ],
            "OxC": [
                "B2 R2 B' L' B R2 L' F' L B' L' F L2 B'",
                "B2 R2 B' L' B R2 B' L2 F L' B' L F' L'",
                "R2 U' B2 R F R' B R' D R2 D' F' R B R2",
                "R2 F2 R' B' R F2 R' B2 L B' R' B L' B'",
                "R2 F2 R' B' R B' F2 L' B R' B' L B2 R'",
                "F2 U' R2 L2 D' L' D R F2 L2 U L U' R F2",
                "B2 L2 B2 U' B' U2 F' D2 F' D B2 D F2 U2 B'",
                "L2 D F D F2 D' F U' F D2 B D2 F D' B'",
                "B2 R2 B' L' B R2 L' F' L B' L' F L2 B'",
                "B2 R2 B' L' B R2 B' L2 F L' B' L F' L'",
                "L' B2 R B R2 U2 R U R' U2 R B L",
                "R B L U2 L' U L U2 L2 B L B2 R'"
            ],
            "AsO": [
                "B' U L' B2 L U B' U' R B R2 U R B2",
                "F' B' U' B U' B L2 B' U' L2 U F' L2 F2",
                "F U2 B L2 D L' F2 L F L D' B' L F'",
                "F U2 L F' D R F' R' D' L B L B' L",
                "F U2 L2 D F' D' L2 F' L2 B L2 B2 U B",
                "F U' R' U2 R U F' R' U' R U R' U R",
                "B U B' U R' F' U' L' U' L U2 F U R",
                "B U L U2 L' U' B' R' U' R U R' U R",
                "B2 U B L' B' L U' B' U B' U R' U R",
                "B2 L U' F U F' L' B' U B' U R' U R",
                "B' U' B U' R B' L' B L R' U2 R B R'",
                "R B' D' R D' L' F' L D2 F R F' R B"
            ],
            "OsC": [
                "F2 L2 B2 D F2 R2 F' D' B' L2 F2 U' F' U B'",
                "L2 D L2 D2 R2 F2 D' L U' F2 D R' B2 D R'",
                "F2 R2 B2 D' F2 L2 F D B R2 F2 U F U' B",
                "R2 D' R2 D2 L2 F2 D R' U F2 D' L B2 D' L",
                "F2 U2 B' U2 B L2 F' L2 U2 F' U2 F'",
                "F2 U2 F' L2 B D2 F' D2 L2 B' U2 F'",
                "F2 U2 B U2 B' R2 F R2 U2 F U2 F",
                "F2 U2 F R2 B' D2 F D2 R2 B U2 F",
                "L' B L' D2 R F' R' D2 L2 B'",
                "F2 B' R2 U2 L2 F2 B2 R' F R' D2 L B' L",
                "F B L2 F U2 B' R2 F' B2 L2 D2 B R2 B",
                "L' B L U2 R2 F R' U2 L2 B R2 D2 R L2",
                "R2 D B' L' D2 R2 F' R2 D' L D2 R' B R'",
                "L2 D' B R D2 L2 F L2 D R' D2 L B' L",
                "R2 L F2 R2 U L2 B2 R' D R2 B2 L U R'",
                "R B' R D2 L' F U2 R2 L2 D2 L U2 L2 B",
                "B L2 B D2 R2 F' B2 L2 B' U2 F R2 F B",
                "B R2 U2 R D2 R2 L2 U2 F R' D2 L B' L",
                "R' L2 F2 L2 U' R2 B2 L D' L2 B2 R' U' L",
                "B' L2 U2 L' D2 R2 L2 U2 F' L D2 R' B R'",
                "B' R2 B' D2 L2 F B2 R2 B U2 F' L2 F' B'",
            ],
            "OxO": [
                "B U' R B2 R' U' B U L' B' L2 U' L' B2",
                "F2 B D' B D F D2 F' R2 D' F D' F B2",
                "L' U2 L2 U L2 U R' U2 L' F2 L2 R' F2 R2",
                "F U' L D F D' L' F2 R' F' R2 U' R' F2",
                "F U' L F2 L' U' F U R' F' R2 U' R' F2",
                "F' U L U2 L' U' F L U L' U' L U' L'",
                "B U B' U L' B R B' L R' U2 L' B' L",
                "B2 U' B' R B R' U B U' B U' L U' L'",
                "B2 R' U F' U' F R B U' B U' L U' L'",
                "B' U' B U' L F U R U R' U2 F' U' L'",
                "B' U' R' U2 R U B L U L' U' L U' L'",
                "L' B D L' D R F R' D2 F' L' F L' B'"
            ],
            "CxO": [
                "L2 F2 L B L' F2 L B2 R' B L B' R B",
                "L2 F2 L B L' B F2 R B' L B R' B2 L",
                "F2 U R2 L2 D R D' L' F2 R2 U' R' U L' F2",
                "B2 R2 B2 U B U2 F D2 F D' B2 D' F2 U2 B",
                "R2 D' F' D' F2 D F' U F' D2 B' D2 F' D B",
                "B2 L2 B R B' R L2 F R' B R F' R2 B",
                "L2 U B L' U L' U' B' F U2 F' U' L' U' L'",
                "F2 U L B2 R' L' U' F2 U F2 R F2 L B2 L'",
                "L2 U B2 L' F' L B' L D' L2 D F L' B' L2",
                "L2 U' L' U L2 U' L' U2 R L' U' L' U R' L2",
                "L' B' R' U2 R U' R' U2 R2 B' R' B2 L",
                "R B2 L' B' L2 U2 L' U' L U2 L' B' R'"
            ],
            "OsO": [
                "L2 F2 L' U F2 U' R' F2 R U' R U' R' L'",
                "B2 L2 B' U L2 U' F' L2 F U' F U' B' F'",
                "F2 R U R2 F R F2 L D F' D' L' U F'",
                "F2 R U R2 F R U' F' U L F2 L' U F'",
                "L2 B2 R2 L B2 R U2 L U' R2 U' R2 U2 R",
                "R' F R U2 R' L F L' F' R U' F U' F'",
                "R U R' U F' U F' U' L F' L' F U F2",
                "R U R' U F' U F' L' B' U B U' L F2",
                "R U B U2 L U' L' U' B' R' U F' U F",
                "R U R' U R U' R' F' U' L' U2 L U F",
                "R U R' U R U' R' B' U R U2 R' U' B",
                "F R B' R B D2 L B' L' D' R D' F' R"
            ]
        },

        "4": {
            "AsA": [
                "B2 F2 D' B2 L2 B' R2 F U2 B' D2 F' D B2 F2",
                "B2 F2 D' F2 R2 F' D2 B U2 F' R2 B' D B2 F2",
                "R2 L2 D R2 L2 U' R2 F2 R' B2 L D2 R' U2 L'",
                "R2 L2 D R2 L2 U' L2 B2 L' U2 R D2 L' B2 R'",
                "B2 F2 U' R2 B2 R' D2 L U2 R' B2 L' U B2 F2",
                "B2 F2 U' L2 F2 L' B2 R U2 L' D2 R' U B2 F2",
                "B2 F2 D' B2 L2 B' R2 F U2 B' D2 F' D B2 F2",
                "B2 F2 D' F2 R2 F' D2 B U2 F' R2 B' D B2 F2",
                "R2 L2 D R2 L2 U' R2 F2 R' B2 L D2 R' U2 L'",
                "R2 U F R' B2 D' F2 L' F' D B2 F2 R'",
                "R2 U F R' B2 D' F2 L' F' D B2 F2 R'"
            ],
            "OsA": [
                "R2 U B U' F2 U B' D2 B2 D' B2 D' B2 D' L2 F2 D B2",
                "R2 U' R' D L2 D' R' D L2 R2 D' F2 U F2 R2",
                "R2 D' F' D B2 D' F' D F2 B2 U' F2 U F2 R2",
                "F2 U' F' D B2 D' F' D F2 B2 D' L2 U L2 F2",
                "F2 D' L' D R2 D' L' D L2 R2 U' L2 U L2 F2",
                "L2 U' F2 R' D' L2 D R B2 U F2 U' B2 L2 F2",
                "L2 D' L2 F' D' B2 D F R2 D F2 U' B2 L2 F2",
                "F U F L2 B2 D2 F D' F' D' B2 L2 F2",
                "L' F' U L U L' U2 L U L' F L"
            ],
            "AsO": [
                "B' U D2 F U' F' D2 R2 D' F D R2 B",
                "L2 U F' B L2 F B2 U F2 U' B U F2 L2",
                "R' U D2 L U' L' D2 F2 D' L D F2 R",
                "B' U D2 F U' F' D2 R2 D' F D R2 B",
                "L U' B' R' D' F2 D R B U R U2 L' R'",
                "L2 U F' B L2 F B2 U F2 U' B U F2 L2",
                "L' R D B D2 B2 D L B' R' U' B2 U2 B'",
                "R' U' R U L U2 R' U' L' U' L R U2 L'",
                "R' U' R U L U2 R' U' R U2 L' R' U R",
                "R' U' R F U' R' U' R U F' U R' U R",
                "R' D' F U B U2 F' U' F U2 F' B' D R",
                "R' D' F L U' F' U' F U L' U F' D R"
            ],
            "CsA": [
                "R D' R2 B2 D B2 U R B2 D' B2 U' R2 D",
                "D R D' R2 B2 D B2 U R B2 D' B2 U' R2",
                "R D' R2 B2 D B2 U R B2 D' B2 U' R2 D",
                "D R D' R2 B2 D B2 U R B2 D' B2 U' R2",
                "R D' R2 B2 D B2 U R B2 D' B2 U' R2 D",
                "D R D' R2 B2 D B2 U R B2 D' B2 U' R2",
                "R D' R2 B2 D B2 U R B2 D' B2 U' R2 D",
                "D R D' R2 B2 D B2 U R B2 D' B2 U' R2",
                "F B U2 B R2 D F' L2 F D' R2 F' B2",
                "L U' L' U D F2 U R U2 R' F2 D' L",
                "R2 B2 R' U2 R' U' R2 B2 R2 U' R B2 R'"
            ],
            "OsO": [
                "R2 F2 R L F2 R F2 R2 L' F2 R' U2 R'",
                "L2 B2 R' F2 R' F2 R2 B2 L' U2 L2 U2 L",
                "F R D' R2 D' L2 D R2 D' L2 D2 R' F'",
                "F' L2 B D F D' B D F' D' B2 L2 F",
                "R F2 B2 L F2 L' B2 R' L2 D2 L' D2 L'",
                "B' D2 F R B R' F R B' R' F2 D2 B",
                "R' L' B2 U2 R B2 R' B2 U2 L' B2 R L2",
                "L' B2 L' D2 L' U2 L D2 L' U2 L2 B2 L",
                "B2 L2 B2 L U2 R' L2 U2 L F2 L2 F2 R",
                "R2 L' D2 R' B2 R' B2 R D2 R2 L U2 R",
                "R' L2 F2 R' D2 R' D2 R F2 R L2 U2 R",
                "B2 R L2 F2 R F2 R' D2 R' D2 L B2 L",
                "B R2 F2 R' B2 L2 B' R' B2 R' F2 R L2",
                "B' R2 F2 R' B2 L2 B R' B2 R' F2 R L2",
                "F' B' D2 B2 U' F2 U' B2 D R2 D F' B",
                "L2 F2 R' F2 R2 L2 U2 L' B2 L B2 U2 R'",
                "R2 F2 R2 U R B2 U' R F2 R' U B2 R'",
                "L2 B2 L2 U2 R2 L' B2 R U2 R' B2 R2 L",
                "L2 U2 F2 D2 F' U' F D2 F' U F' U2 L2",
                "R2 D2 U' F U' B2 U F' U' B2 D2 U2 R2",
                "L B2 D' B D' F2 D B' D' F2 D2 B2 L'",
                "L2 F2 L' F2 R D2 L' U2 L D2 U2 R' L'",
                "F2 B2 L2 F2 L' B2 L F2 L' B2 L' F2 B2",
                "R L D2 R L2 D2 R2 L' B2 R L2 B2 R'",
                "B R2 F2 R' B2 L2 B' R L2 F2 R' B2 R'",
                "B' R2 F2 R' B2 L2 B R L2 F2 R' B2 R'",
            ],
            "OxC": [
                "F2 D R' D' R2 U D R2 D' R U' R2 F2",
                "R2 U' B' R2 F' B U' B2 U' F U B2 R2",
                "B2 U L2 D' L' B2 L D L' B2 L' U' B2",
                "B2 U' R2 D L U2 L' D' R B2 R U B2",
                "B2 D' F2 D B U2 B' D' F R2 F D B2",
                "B2 U' R2 D L U2 L' D' R B2 R U B2",
                "B2 D' F2 D B U2 B' D' F R2 F D B2",
                "B2 U' R2 D L U2 L' D' R B2 R U B2",
                "B2 D' F2 D B U2 B' D' F R2 F D B2",
                "B' U2 F U F' U2 B2 U' F U B' U F'",
                "B' U2 B' D' F R2 F D B D' F2 D B",
                "L R F U2 R' U' R U' F' U' L' U R'"
            ],
            "CxO": [
                "B U' D2 F' U F D2 L2 D F' D' L2 B'",
                "R2 U' F B' R2 F' B2 U' F2 U B' U' F2 R2",
                "L U' D2 R' U R D2 F2 D R' D' F2 L'",
                "B U' D2 F' U F D2 L2 D F' D' L2 B'",
                "L U L' U' R' U2 L U L' U2 L R U' L'",
                "L U L' U' R' U2 L U R U L' R' U2 R",
                "L U L' F' U L U L' U' F U' L U' L'",
                "L D F' U' B' U2 F U F' U2 F B D' L'",
                "L D F' R' U F U F' U' R U' F D' L'",
                "L' R D' B' D2 B2 D' R' B L U B2 U2 B",
                "R2 U' F B' R2 F' B2 U' F2 U B' U' F2 R2",
                "R' U B L D F2 D' L' B' U' L' U2 L R"
            ],
            "AsC": [
                "F2 D' L U' L2 U D L2 U' L' U L2 F2",
                "F2 D' L D L2 U' D' L2 D L' U L2 F2",
                "L2 U B L2 F B' U B2 U F' U' B2 L2",
                "B2 U L2 D' R' U2 R D L' B2 L' U' B2",
                "B2 D F2 D' B' U2 B D F' L2 F' D' B2",
                "B2 U L2 D' R' U2 R D L' B2 L' U' B2",
                "B2 D F2 D' B' U2 B D F' L2 F' D' B2",
                "B U2 F' U' F U2 B2 U F' U' B U' F",
                "B U2 B D F' L2 F' D' B' D F2 D' B'",
                "B2 U L2 D' R' U2 R D L' B2 L' U' B2",
                "B2 D F2 D' B' U2 B D F' L2 F' D' B2",
                "L' R' F' U2 L U L' U F U R U' L"
            ],
            "OsC": [
                "L' D L2 B2 D' B2 U' L' B2 D B2 U L2 D'",
                "D' L' D L2 B2 D' B2 U' L' B2 D B2 U L2",
                "L' D L2 B2 D' B2 U' L' B2 D B2 U L2 D'",
                "D' L' D L2 B2 D' B2 U' L' B2 D B2 U L2",
                "L' D L2 B2 D' B2 U' L' B2 D B2 U L2 D'",
                "D' L' D L2 B2 D' B2 U' L' B2 D B2 U L2",
                "L' D L2 B2 D' B2 U' L' B2 D B2 U L2 D'",
                "D' L' D L2 B2 D' B2 U' L' B2 D B2 U L2",
                "F' B' U2 B' L2 D' F R2 F' D L2 F B2",
                "L2 B2 L U2 L U L2 B2 L2 U L' B2 L",
                "R' U R U' D' F2 U' L' U2 L F2 D R'"
            ],
            "CsC": [
                "F2 R2 D B2 R2 U R2 U' B2 R2 F' U F D' F' U' F'",
                "L2 U' F2 U F2 L2 D F U F D' F' U' F'",
                "D2 U2 R2 B2 R2 D2 U2 L' B2 L' F2 L B2 L",
                "B2 F2 R2 F2 R2 B2 F2 L' B2 L' F2 L B2 L",
                "R2 B2 L2 B2 R2 L2 F2 L' B2 L' F2 L B2 L",
                "R2 B2 L2 F2 R2 L2 B2 L' B2 L' F2 L B2 L",
                "L2 B2 R2 L2 B2 F2 R2 L' B2 L' F2 L B2 L",
                "B2 R2 L2 F2 L2 B2 R2 L' B2 L' F2 L B2 L",
                "F2 R2 L2 B2 L2 B2 R2 L' B2 L' F2 L B2 L",
                "B U' B2 U2 B' U' F' U B U' F U' B2 U B'",
                "F U F2 U L U L' U' F2 U L U' L' U2 F'",
                "L' U B' U' F U' B U F' U' B' U2 B U' L",
                "R' U F' U2 F' U B U' F U B' U F U' R",
                "L' U' B U L U' B' U' L U' F U2 F' U' L'",
                "B' U' R' U' F' U L' U2 L U F U R U' B",
                "L' U' B' U2 B U F U' B' U F' U B U L",
                "L' U2 L U F U2 F U R' U' F' U R U F'",
                "F2 R F' U' F U F R' F U F2 U2 F' U2 F'",
                "F U L' U2 R U L U' R' U L' U L U' F'",
                "L' U2 L U' F U' R' U' F U R U' F' U2 F'",
                "L U' F2 U F' U' F' U L F L' F2 L F L2",
                "L F L U L' F2 L U' L' U F2 U' F' L'",
                "L' U2 L U' B' F R2 B R' U' R2 U R F'",
                "L' U2 L U' B F' L2 F L U L2 U' L' B'",
                "L' U2 L2 U L B' L U L U' L' B L2 U' L'",
            ],
            "CsO": [
                "L' D F2 U F2 L2 U' L' U D2 R2 D' R2 D' L2 D'",
                "L' D F2 U F2 L2 U' L' U2 D F2 D' F2 U' L2 D'",
                "L' D F2 U F2 L2 U' L' U' L2 D' L2 U2 D L2 D'",
                "L' D F2 U F2 L2 U' L' D' B2 D' B2 U D2 L2 D'",
                "R2 U F2 L D R2 D' L' B2 U' F2 U B2 R2 F2",
                "R2 D R2 F D B2 D' F' L2 D' F2 U B2 R2 F2",
                "F' U' F U2 B2 L2 F D F D' F2 L2 B2",
                "F' U' F' R2 B2 D2 F' D F D B2 R2 F2",
                "R F U' R' U' R U2 R' U' R F' R'"
            ],
            "OxO": [
                "B L2 F B' U' F' U2 B2 R2 F' D' F R2 B2",
                "B' R2 F' B U F U2 B2 L2 F D F' L2 B2",
                "R B2 L R' U' L' U2 R2 F2 L' D' L F2 R2",
                "L' B2 L R' U R U2 L2 F2 R D R' F2 L2",
                "F L F' R' F R F R' F R F' L' F'",
                "F R U' R' U R U R' U R U' R' F'",
                "F' L' U L U' L' U' L U' L' U L F",
                "F' R' F L F' L' F' L F' L' F R F",
                "L U2 L D' B2 L' B2 L U B2 U D L'",
                "L' B2 R' F D2 R D2 R' B' D2 F' B' L",
                "R B2 L F' D2 L' D2 L B D2 F B R'",
                "R' U2 R' D B2 R B2 R' U' B2 U' D' R"
            ]
        },

        "5": {
            "AsA": [
                "R2 F2 D L B2 L D2 R D' L2 D2 R' F2 R2",
                "D2 B2 D L D' B2 U' R' U' R D2 L' U L",
                "F2 L2 U B U2 F L2 F U' F2 U2 B' L2 F2",
                "B2 R2 D F L2 F D2 B D' F2 D2 B' R2 B2",
                "L2 D F D' L2 U' B' U' B D2 F' U F D2",
                "F2 U2 F' U' F L F L' U' F' L' U2 L F'",
                "F2 U2 F' U' F' U' R' F R F L' U2 L F'",
                "F2 U2 F' U' F L F L' U' F' L' U2 L F'",
                "F2 U2 F' U' F' U' R' F R F L' U2 L F'",
                "L D F' U R2 U2 R' U2 R' F D' U' L' F'",
                "F2 U2 F' U' F L F L' U' F' L' U2 L F'",
                "F2 U2 F' U' F' U' R' F R F L' U2 L F'"
            ],
            "AsC": [
                "B U' F' L U' L' U F U2 L U2 L' B'",
                "R D L' R' B2 L R' U R U R2 D' R2",
                "B2 U B2 U' B' U' R B2 U B2 U' R' B'",
                "L D' L U' L' D L D' B2 U B2 D L2",
                "L D' L U2 L2 D F2 U F2 D' L D L'",
                "R D B2 R2 U L R U2 L' U R2 D' R2",
                "B U L' B2 R2 F D' F' R' B2 L B' R'",
                "L' U' L U2 R' U L' U L U' L' U2 L R",
                "B U R' U2 L U' L' U' L U' R U' L' B'",
                "R2 F' R U' R U2 R' U F U2 F' R' F R2",
                "L' B' U' B U L F U2 F' U2 F' L F L'",
                "B U' L B' L' U' B U2 B' U' L B L' B'",
                "B2 U2 L U' B U B' L' U' B' U' B' U B'",
                "L' U' L' U' L U F R U2 R' U' F2 L F",
                "F R' B R U' B' U B R' B2 R' B R2 F'",
                "L' U' L' U R D' U' B2 D L U L U2 R'",
                "L' R D B D' R' B L U' B' U' B' U B",
                "B U' B' U' L F L' R2 B' R2 B L F' L'",
                "R' U F' L' U' R U R' U2 L U R' F R2",
                "B' U' R' U2 R U' R2 D' R U' R' D R2 B",
                "L2 B' R B L B2 R' B2 U B' U' B U' L",
            ],
            "OsA": [
                "R2 D' L2 D' L2 D2 R' U R' F2 U F2 R U' R'",
                "B2 D' F2 D' F2 D2 B' U B' R2 U R2 B U' B'",
                "B2 U' B2 U L2 U' R' U L2 U' L U2 R L' U B2",
                "B2 D' R2 U B2 U' F' U B2 U' B U2 B' F D B2",
                "L2 B2 F2 D U F D' F' U' B2 F2 L2 B' U B",
                "B2 R2 B2 U' B2 R2 F D' R D R' B2 F' L U' L'",
                "D U2 L2 U2 F2 U2 L' F2 L D U' F2 D2 L' U L'",
                "L2 D2 F2 D' U L' F2 L D U' F2 D2 L' U L'",
                "D F2 D2 R B2 R' D2 F2 D' U L U L'",
                "R' L F2 U' F2 U F2 R U L'",
                "B' F R2 U' R2 U R2 B U F'",
                "R' L F2 U' F2 U F2 R U L'"
            ],
            "CsA": [
                "L2 U' L2 F' L2 F U2 L2 F U2 F' U' L2",
                "L R U2 L' B2 R U R' B2 R U' B2 R2",
                "L2 U L2 U' L2 U' B' D2 F U2 F' D2 B",
                "R D L2 D' U2 L' R B2 L D L2 D' R2",
                "L2 R D R' F2 R D L R2 D2 L U2 R",
                "L2 R D R' F2 R D L' U2 L D2 L2 R'",
                "R D L2 D' L U2 L' R B2 D L2 D' R2",
                "B2 L2 B' F' D2 B2 D B2 D L2 F U B'",
                "L2 D F2 U' F2 D' B' D2 F U2 F' D2 B",
                "F U' F' U' R U' F U' F' R' U' R U' R'",
                "F U' F' U2 B F U' F' U' B' U' B U' B'",
                "F U' B U B' F' U2 B U' B' U' B U' B'",
                "B' U2 B L U F U2 F' U' L' U' B' U B",
                "B' U2 B R U' B' U2 B U R' U' B' U B",
                "L' B' U2 B U2 R U B' U' B U' L U R'",
                "F' U2 F2 U2 F2 U' F' R' F' U' F2 U F R",
                "B' U2 B U' R' B' R U2 R' B R B' U B",
                "L' R' U' B L' B' L U L R U2 B U' B'",
                "L2 U L U L D' L U' L' D U' L' U2 L'",
            ],
            "CsC": [
                "F U F' U' B U2 B' U2 B L2 B L2 B2",
                "F U' L' B' U' B L F R U2 R' U' F2",
                "F2 B' R U' R' U B U2 R U2 R' U' F2",
                "B L' U R D' B' D R' U' L' B L2 B2",
                "L2 R' U L2 U' L2 R B2 R2 D' F2 D R2 B2",
                "L2 R' U L2 U' R F2 B2 D R2 D' F2 B2 L2",
                "R B2 R' U R B2 R F2 L' D' L F2 R2",
                "F R B2 R' F' U L U R' U2 L' R B2",
                "F R B2 R' F' U L U' L' R B2 R'",
                "F2 D B' R2 F' B U' F D' F' U' F'",
                "R F' B2 U L U' L' U' F U B2 R'",
                "R B2 U F L F' U' F L' F' B2 R'"
            ],
            "CsO": [
                "D F B2 U' B2 U F' B2 L2 U L2 D' B2",
                "F B2 U' B2 U F' B2 L2 U L2 D' B2 U2 D",
                "F R2 D' F D' L2 F' D2 R2 F' U B'",
                "F2 R' B' R F' B R B' R B R' F'",
                "B2 L' F' L F B' L F' L F L' B'",
                "R B2 D' R D' F2 R' D2 B2 R' U L'",
                "F R2 D' F D' L2 F' D2 R2 F' U B'",
                "F R' F' U2 F B' R' B R F' R' U2 R",
                "F R' F' U2 R' D R B' R' B U2 D' R",
                "F2 R' B' R F' B R B' R B R' F'",
                "R2 D2 L D' L' D L' D2 R' U B2 U' R'",
                "R' F' R' D R U2 B' R' B U2 D' R F"
            ],
            "OxC": [
                "R' F2 B D' F U F' D F U' F B' R",
                "R' F2 B2 D' F U F' D F U' F B2 R",
                "R' F2 B' D' F U F' D F U' F B R",
                "R' F' U B D' B' U B D B' U2 F R",
                "R' F' U2 R D2 R' U R D2 R' U F R",
                "R' F' L' F R F U' R' F R F2 U L",
                "R' D2 F R' F L' F' R F L F2 D2 R",
                "R' D' L' F' L' B' L F L' B L2 D R",
                "R' L F D' F' L F L' D L F' R L2",
                "B L' B' R L U B2 R B R' U' B R'",
                "B2 U B L D2 L' B' U' B L D2 L' B",
                "L' B' R U2 R2 U' R B R U2 L U R'",
                "B U L' U' L' D' L U L' D L2 U' B'",
                "R U R' U2 R B U' B' U2 B U' B' R'",
                "B' L' B' U F U' B2 U F' U' B' L B"
            ],
            "AsO": [
                "L U B' R B L' B' R' B U L U2 L'",
                "R' U2 F' L F R F' L' F U R' U R",
                "L R2 F2 R F2 D R U' R' D' U L' R",
                "L2 F U F' U' R' F2 D F D' F L2 R",
                "B L U' R' F2 R F2 U L' B' R U2 R'",
                "L U' R U2 L' U' B2 R' U2 R U2 B2 R'",
                "L' B F2 D L2 D' B2 F U B U2 F L",
                "B2 D F2 D' F' L2 F D' B D' F2 D2 B",
                "L' B2 D2 F2 R' F2 D' L D' B2 R' U2 R",
                "R' U2 B2 D2 L' F2 D' L D' B2 R' U2 R",
                "B U' B' U2 B U' B' R' U R U2 R' U R",
                "B U' B' U2 B U L U L' U2 L U L' B'",
                "L R' U L' U2 R U2 L U' L' U' R' U R",
                "R' U' F U F' U' R U F U' F' R' U R",
                "B U2 B' R' U R U2 R' U R U B U2 B'",
                "L' U L U' F' U2 F' R' F2 R' B' R' B R'",
                "L' U' L2 F U F' U' F' L' F' R' F' R F'",
                "B L F' L' B' F U L' U' L U F U2 F'",
                "R' U2 R U B U B' F R' F' U F R F'",
            ],
            "OsC": [
                "R D L2 D' R' F2 L2 U R2 B2 L2 D2 L2 D' R2",
                "R D L U2 D2 R D' L' F2 L2 D' L2 B2 D' R2",
                "R D L2 D' R' F2 L2 U R2 B2 L2 D2 L2 D' R2",
                "R D L U2 D2 R D' L' F2 L2 D' L2 B2 D' R2",
                "R D L2 D' R' F2 L2 U R2 B2 L2 D2 L2 D' R2",
                "R D L U2 D2 R D' L' F2 L2 D' L2 B2 D' R2",
                "R D L2 D' R' F2 L2 U R2 B2 L2 D2 L2 D' R2",
                "R' U2 R U2 D' R U' R U R U' R2 D",
                "D R' U2 R U2 D' R U' R U R U' R2",
                "R' U2 R U2 D' R U' R U R U' R2 D",
                "D R' U2 R U2 D' R U' R U R U' R2",
                "L' U2 F2 D' L D F2 R U' R' U2 L"
            ],
            "OxO": [
                "R U' R' F2 U2 F2 R' D R U R2 D' R2",
                "R U' R' F2 U2 F2 R' D R D B2 D' B2 D'",
                "R D L2 D' R D2 F2 U L2 U' D2 R2 U B2",
                "R D R2 U2 L' B2 L U R D2 F2 U2 F2 D",
                "D F2 B U' F2 U B' L2 D' B2 U B2 L2",
                "F2 B U' F2 U B' L2 D' B2 U B2 L2 D",
                "B U' B' R2 U2 R2 B' D B U B2 D' B2",
                "D F B2 U' B2 U F' R2 D' F2 U F2 R2",
                "D R D R2 U2 L' B2 L U R D2 F2 U2 F2",
                "D' R U' R' F2 U2 F2 R' D R D B2 D' B2",
                "R' B' R F R F' R2 F R D R' D' B F' R",
                "F U F' D U' B' D' U2 F U2 F' D U2 B D'",
                "F U F' U B' U' R' U F R B U R' F' R",
                "B U2 F' U' B L2 B' L2 B' U' F U F' U F",
                "F U2 L' U B U' B' U' L F' L' R' U2 L R",
                "F U F' U B' U' R' U B L' B' U R B L",
                "L R2 F2 L' R U2 F U F U F' U2 F' U R",
                "R' F' U' F U R2 B' U' B2 U' B2 U2 B U' R'",
                "L F2 L' R U2 R2 F U F U F' U2 F' U R",
                "F U F' L' R' U2 R U R' B' U' B L U R",
                "F U F' U' F' U' F' L R' D' F D L' F R",
                "L' F' L U L' B' F R B U' B' U R' B L",
                "R' B' R U2 B L B' R' B L' R U B' U B",
                "F R2 F' R' B U2 B' U2 B' R' B U F' U F",
            ],
            "CxO": [
                "R2 B2 F2 D' B2 U B D' B2 U' B2 D B' F2 R2",
                "F2 R2 U B D B U' B' D' B' L2 D' R2 L2 F2",
                "F2 R2 F2 U B' F2 R2 B D B' R2 B D' R2 F2",
                "R2 B' U B2 U' R2 U R2 B' R2 B' U' B",
                "B2 L' U L2 U' B2 U B2 L' B2 L' U' L",
                "R2 B' U B2 U' R2 U R2 B' R2 B' U' B",
                "F U2 L' B' R' U2 R' B' R2 B2 L2 F' L'",
                "L U2 B' R' F' U2 F' R' F2 R2 B2 L' B'",
                "B2 L' U L2 U' B2 U B2 L' B2 L' U' L",
                "F U2 F' L2 U' L2 U' L2 U2 L2 U2 F U' F'",
                "R2 B' U B2 U' R2 U R2 B' R2 B' U' B",
                "F U2 L' B' R' U2 R' B' R2 B2 L2 F' L'"
            ],
            "OsO": [
                "B L' B' R B2 L D B D2 R D R2 B",
                "L2 U L D R' U' F2 U R D' L U' L2",
                "L B2 L R' U' L2 U' L2 R' D L2 D' R2",
                "L2 U' L2 B' U2 B U2 L2 B L2 B' U' L2",
                "B2 D F L2 F D F D B D' F D2 B",
                "L' R D L' D' B2 R D L D' R2 U2 L",
                "R' B2 U R' B2 R U R' B2 R U2 B2 R",
                "L2 D F D B' U' R2 U B D' F D' L2",
                "F2 L2 R2 U B' D B U' L2 R2 F' U' F'",
                "F2 D U R D' L D2 R D L B2 D L2",
                "B U B' U B U' B' U' F' U B U' B' F",
                "B2 U B' L U2 L' U L U L' U B U' B2",
                "R' U2 F' U L' U L U L' U2 L F U R",
                "B R D' R' U R U R' U R D U2 R' B'",
                "F R F' R' U' R F U R' U' B' R B F'",
                "F U' B' R F R B F' R' U' R' U R F'",
                "B U L U2 L' U2 B' U F R B' R' B F'",
                "L F U2 F' U' L' U' L R' F' L F L2 R",
                "B L' B' R B2 L B R B R2 U F' U F",
            ]
        },

        "6": {
            "OsA": [
                "L2 B2 D F2 D' B2 L U2 L' D F2 D' L U2 L",
                "D2 U2 R2 D' F' D R2 U B U B' D2 F U' F'",
                "L2 F2 D' R' B2 R' D2 L' D R2 D2 L F2 L2",
                "R2 B2 U' L' U2 R' B2 R' U R2 U2 L B2 R2",
                "L2 F2 D' R' B2 R' D2 L' D R2 D2 L F2 L2",
                "R2 B2 U' L' U2 R' B2 R' U R2 U2 L B2 R2",
                "L2 F2 D' R' B2 R' D2 L' D R2 D2 L F2 L2",
                "R2 B2 U' L' U2 R' B2 R' U R2 U2 L B2 R2",
                "F' U' F U2 B' R2 U F' U F U' B' R2 B2",
                "L2 F2 D' R' B2 R' D2 L' D R2 D2 L F2 L2",
                "R' L2 D R' D2 L B2 D' R D L' D R L2",
                "R2 B2 U' L' U2 R' B2 R' U R2 U2 L B2 R2"
            ],
            "OxC": [
                "F' D' B2 D B' U2 B F' L2 D' B2 D F2",
                "L2 B2 L R D2 L2 D' L2 D' B2 R' U' L",
                "B2 D' R2 U R2 D L D2 R' U2 R D2 L'",
                "R' U R U F' U R' U R F U F' U F",
                "R' U R U2 L' R' U R U L U L' U L",
                "R' U L' U' L R U2 L' U L U L' U L",
                "L U2 L' F' U L U2 L' U' F U L U' L'",
                "L U2 L' B' U' R' U2 R U B U L U' L'",
                "B L U2 L' U2 F' U' L U L' U B' U' F",
                "R U2 R2 U2 R2 U R F R U R2 U' R' F'",
                "B F U L' B L B' U' B' F' U2 L' U L",
                "L U2 L' U F L F' U2 F L' F' L U' L'",
                "B2 U' B' U' B' D B' U B D' U B U2 B",
                "B F L F U' F' U L' B' F' U2 L' U L",
                "F L' B' U B L U F U2 F2 U2 L' U L",
                "B F' U B' L' U2 L B L' U2 L U' B' F",
                "F2 U L' R U R' U' L U' F2 U2 L' U L",
                "B F' D' B D B2 F U' B' U' B F' L2 F",
                "L' B U B U' R' U2 B' U2 B U R B2 L",
            ],
            "OsC": [
                "L' F U2 F' U' F U' R' F' L F R F'",
                "B' U' L F' L' B L F L' U' B' U2 B",
                "F U2 R B' R' F' R B R' U' F U' F'",
                "B' F2 R2 F' R2 D' F' U F D U' B F'",
                "B2 R' U' R U F R2 D' R' D R' B2 F'",
                "L' B' U F R2 F' R2 U' B L F' U2 F",
                "B' U F' U2 B U L2 F U2 F' U2 L2 F",
                "B L' R2 D' B2 D L2 R' U' L' U2 R' B'",
                "L2 D' R2 D R B2 R' D L' D R2 D2 L'",
                "B L2 D2 R2 F R2 D B' D L2 F U2 F'",
                "F U2 L2 D2 B R2 D B' D L2 F U2 F'",
                "L' U L U2 L' U L F U' F' U2 F U' F'",
                "L' U L U2 L' U' B' U' B U2 B' U' B L",
                "B' F U' B U2 F' U2 B' U B U F U' F'",
                "F U R' U' R U F' U' R' U R F U' F'",
                "L' U2 L F U' F' U2 F U' F' U' L' U2 L",
                "B U' B' U R U2 R F R2 F L F L' F",
                "B U B2 R' U' R U R B R F R F' R",
                "L' B' R B L R' U' B U B' U' R' U2 R",
                "F U2 F' U' L' U' L R' F R U' R' F' R",
                "R' F' U' F' U F2 R F U' F' U R' F' R",
            ],
            "CsO": [
                "R' D' F2 R2 U' L' R' U2 L U' R2 D R2",
                "R' D' L R F2 L' R U' R' U' R2 D R2",
                "D B' D B' U B D' B' U B2 D' R2 U' R2",
                "F' U L2 D2 R2 U' B' D' B2 U B2 D' L2 R2",
                "F' D' F B L2 F B' U' F' U' F2 D F2",
                "F' D' L2 F2 U' F' B' U2 B U' F2 D F2",
                "B' D B' U B D' B' U B2 U' B2 U' B2",
                "B' D B' U B D' B' U B2 D' R2 U' R2 D",
                "B' D B' U B D' B' D L2 U' L2 D' B2",
                "B' D B' U2 B2 U' B2 U' B2 U B' D' B",
                "B' D B' U2 B2 D' R2 U' R2 D B' D' B",
                "L2 U' L2 U L U F' L2 U' L2 U F L"
            ],
            "AsC": [
                "R' F U' R' U R U F' R' U2 R U2 R",
                "R' U2 B U' L' U L U B' L' U2 L R",
                "R' U' R U R' F2 R U2 R' U2 R' F2 R2",
                "L R2 F' U F U' L' U2 F' U2 F U R2",
                "R' U L' U' R U B2 U' R' U R B2 L",
                "L2 D' B U B U' B' D U' L2 F U' F'",
                "R' F U' R' U R U F' L' B2 R B2 L",
                "R' U B L U L' B' R' F' U2 F U R2",
                "R' F' L2 F R U' B' U' F U2 B F' L2",
                "F' L2 U F U2 B' U B U2 F' U2 L2 F",
                "R' U L F2 D' L' U' L' U2 L2 D L' R",
                "R' U' R U R' F2 L F2 R' F2 L' F2 R2",
                "F' L2 R2 B L' B D B' D' B' L' R2 F",
                "R2 U F U L' F' U2 F U2 L U' F' R2",
                "L' B U' F' D L D' F U B L' B2 L2",
                "R2 D' F2 L' R U2 L U' R' D R U R",
                "B' U2 B2 L2 D L' U L2 D' L2 U' L' B'",
                "B' U2 B2 L2 D L' D F2 D' F2 D' L' B'",
                "F' L2 F U' F' L2 F' R2 B D B' R2 F2",
                "L' D L' U' L D' U L U' L U L U' L'",
                "L2 U' L2 B' L' U L U' L U L U' L' B",
                "R' U' R U2 L' U L U2 R' U' L' U2 L R",
                "R' U' R U' B' U B U R' B' U2 B U' R",
                "R' U' R U L' U2 L U2 R' U2 L' U2 L R",
            ],
            "AsA": [
                "L U2 L' U2 D L' U L' U' L' U L2 D'",
                "D' F U2 F' U2 D F' U F' U' F' U F2",
                "F U2 F' U2 D F' U F' U' F' U F2 U D'",
                "D' L U2 L' U2 D L' U L' U' L' U L2",
                "L U2 L' U2 D L' U L' U' L' U L2 D'",
                "D' F U2 F' U2 D F' U F' U' F' U F2",
                "F U F D R2 F D' F L2 U D' B' D L2",
                "F U2 F' U2 D F' U F' U' F' U F2 U D'",
                "F U2 F' U' L2 U D' B U B' U' B' D L2",
                "B U2 R2 D B' D' R2 F' U F U2 B'",
                "R U2 F2 D R' D' F2 L' U L U2 R'",
                "B U2 R2 D B' D' R2 F' U F U2 B'"
            ],
            "OsO": [
                "B' U2 L F R U2 R F R2 F2 L2 B L",
                "R' U2 R B2 U B2 U B2 U2 B2 U2 R' U R",
                "F' L F' R' F2 L' F R U2 F' U2 F U2 F'",
                "R' U L F2 L' F U R' F' R F2 U' F' R",
                "F' U2 B2 D' B' D L2 B' U' F U F2 L2 F2",
                "F' U2 F2 U' B' U R2 B' D' F D F2 R2 B2",
                "L2 D' L R2 U2 L' D' R' D' L' D R' D2 L'",
                "F' L D2 U2 R F' R' D2 B' L B U2 L' F",
                "R U L' U R' U' L U' R U R' U2 R U2 R'",
                "R U' R' B U B' U R2 U R' U' F R F' R",
                "R U' F U' R U2 R2 U R2 U R' U F' U2 R'",
                "F' U2 F2 U' B' U B F' U2 F' U' B' U2 B F",
                "F' L2 F2 U F' U B' U B' U B' L2 B U' B2",
                "L' B' U' B2 U L U' L2 B' L' F' L' F2 U2 F'",
                "D R' U R' U2 R' U2 R2 D' U2 R2 U R' U' R2",
                "R' U R' U2 R' U2 R2 D' U2 R2 U R' U' R2 D",
                "F' U2 F2 R' U R U' F' U2 F' R' U2 R U' F",
            ],
            "CxO": [
                "R2 D2 R2 B2 R2 D2 R L U' F2 U' F2 L' U' R",
                "F2 D B2 D B2 D2 F U' F R2 U' R2 F' U F",
                "R2 U2 L2 B2 L2 U2 R' L' U' B2 U' B2 R' U' L",
                "R2 D2 R2 F2 R2 D2 R' L' U' B2 U' B2 R' U' L",
                "L2 U2 R2 B2 R2 U2 R L U' B2 U' B2 R' U' L",
                "L2 D2 L2 F2 L2 D2 R L U' B2 U' B2 R' U' L",
                "R2 B2 F2 D' U' F' D F U B2 F2 R2 B U' B'",
                "B2 D F2 D2 B2 U' R D' F2 D2 U B2 L2 U L B2",
                "B2 D F2 D F2 D2 B U' B L2 U' L2 B' U B",
                "R2 L2 D2 F2 U2 R L' B2 U' F2 U' F2 L' U' R",
                "B2 D2 R' L B2 U' F2 U' F2 L' U' R",
                "R' L F2 U F2 U' F2 L' U' R"
            ],
            "OxO": [
                "F2 B' U F2 U' F2 B L2 U' L2 D F2 D'",
                "D' L2 R' U L2 U' L2 R B2 U' B2 D L2",
                "F R2 D' F2 D2 R2 U B U2 R2 B' D' F2 R2",
                "L2 D' B U' B' U B' U' D B' U B L2",
                "L2 R' U L2 U' L2 R B2 U' B2 D L2 U' D'",
                "R2 U' F D' F' D F' U D' F' D F R2",
                "R2 F L F' L' R F' L F' L' F R",
                "R' F2 D R' D B2 R D2 F2 R U' L",
                "L' B2 D L' D F2 L D2 B2 L U' R",
                "B2 R F R' F' B R' F R' F' R B",
                "R2 F L F' L' R F' L F' L' F R",
                "R' F2 D R' D B2 R D2 F2 R U' L"
            ],
            "CsA": [
                "R' U' R F U' R' U2 F2 D' F' D R F2",
                "F' U F R2 U2 R2 F D' F' U' F2 D F2",
                "R' U' L R2 U2 L D' R' F2 R D L2 R'",
                "R2 D' F2 U' F U F D R2 U2 B U' B'",
                "B2 R' U2 L U R U' L' U2 B2 L U2 L'",
                "R' U' R B2 L2 F' L2 B' L F U L' B'",
                "F R U' R' B2 F2 D' L D2 L' D' B2 F",
                "L2 D' R2 B D B' D' R2 D L2 F U' F'",
                "L2 R' U L2 U' R F2 D R2 U' R2 F2 D'",
                "D' L2 R' U L2 U' R F2 D R2 U' R2 F2",
                "R2 D' R' B2 L2 D L2 B2 R D R U R",
                "B L2 D F' D R2 F R2 F' R2 D2 L2 B'",
                "R2 D2 B' L2 D' B' U B2 D' U' R2 U2 F'",
                "B L2 D F' D R2 F R2 B' D2 L2 U2 F'",
                "R2 D2 B' L2 D' B' D L2 B2 D2 R2 U2 F",
                "F L F' U F L' F' L U L' U' L U' L'",
                "R' U' R U2 F U F' U F U' R' U' R F'",
                "R' F R F' U' F' U F L F U F' U' L'",
                "R' U' R B U B' R B' R' B U B U2 B'",
                "F R U' R' U' F' L F' L' F U F U2 F'",
                "F R U' R' U2 R' U' R2 U R B' R2 B F'",
                "B U' L' U' L' U' L2 U B' L U L2 U' L'",
                "L' U L' R U' L' U R' U2 L' U L U L2",
            ],
            "CsC": [
                "L2 D' R2 F2 D L2 D' F2 R2 F' U B2 U' F D L2",
                "R2 D L2 D' R2 D L2 D' L U' R2 U L' U' R2",
                "R2 U' R2 B2 U L2 U' B2 R2 B' D F2 D' B U R2",
                "D B2 D F2 U' L2 U F2 D' F U' B2 U F' D' R2",
                "R2 D' F2 R2 U B2 U' R2 F2 R' D L2 D' R D R2",
                "R2 U' R2 B2 U L2 D' R2 F2 R' D L2 D' R D R2",
                "D' U F2 D' F2 D U' R' U' R' D R U R",
                "D2 U2 L2 D' L2 D2 U2 R' U' R' D R U R",
                "D U' B2 D' B2 D' U R' U' R' D R U R"
            ],
            "AsO": [
                "L' B L F' L2 B' D' L' D L' F2 U' F'",
                "L' U B' U' B2 F' D L2 D' B' F U L",
                "L' U' F' D' F L U' L' F' D F U2 L",
                "L' B L2 F' L B' D' L' D L' F2 U2 F'",
                "L' B L F' L2 B' D' L' D2 F' D' F2 L'",
                "B2 U' B' D' F U R2 U' F' D B' U B2",
                "B' L2 B' F U B2 U B2 F D' B2 D F2",
                "B2 U B2 L U2 L' U2 B2 L' B2 L U B2",
                "L2 D' R' B2 R' D' R' D' L' D R' D2 L'",
                "B F' D' B D L2 F' D' B' D F2 U2 B'",
                "F L2 U' F L2 F' U' F L2 F' U2 L2 F'",
                "B2 D' R' D' L U F2 U' L' D R' D B2",
                "R2 B2 F2 U' L D' L' U B2 F2 R U R",
                "R2 D' U' F' D B' D2 F' D' B' L2 D' B2",
                "L' U' L U' L' U L U R U' L' U L R'",
                "L2 U' L B' U2 B U' B' U' B U' L' U L2",
                "F U2 R U' B U' B' U' B U2 B' R' U' F'",
                "L' F' D F U' F' U' F U' F' D' U2 F L",
                "R' F' R F U F' R' U' F U L F' L' R",
                "R' U L F' R' F' L' R F U F U' F' R",
                "L' U' B' U2 B U2 L U' R' F' L F L' R",
                "B' R' U2 R U B U B' F R B' R' B2 F'",
            ]
        },

        
    },

    // This is for the U ZBLL set
    "U": {
        "2GLL": {
            "AsA": [
                "F2 D' F' R2 B D2 B' R2 F U B2 U' B2 D L2 F2",
                "F2 D' F' R2 B D2 B' R2 F D L2 U' L2 U L2 F2",
                "R B2 R U' F2 U L' D2 L U' L2 B2 D' L2 F2",
                "B U B' R2 F2 U' F D' F2 D F' U F2 R2",
                "B' R2 D2 L' F' L D2 F2 R' B R F2 R2",
                "R' F2 D2 B' L' B D2 L2 F' R F L2 F2",
                "B' R2 D2 L' F' L D2 F2 R' B R F2 R2",
                "R' F2 D2 B' L' B D2 L2 F' R F L2 F2",
                "F' U' F U2 L R F U F' U2 R' U L'",
                "B' R2 D2 L' F' L D2 F2 R' B R F2 R2",
                "R2 U B2 U' R2 U L U2 R2 B2 D2 R F2 D2 R",
                "R B2 D2 L2 D R D' L2 F2 R' D2 B2 R' U L'",
                "R U2 R' U' F' U F' L F L' U F U F' U F",
                "R U2 R' U' R U' R2 L U L' U L U2 L' U2 R",
                "L U L' U L U2 R L' U2 R2 U' R2 U' R2 U2 R",
                "R U2 R' U' R U' R2 U2 R U B U2 L U L' B'",
                "F' B L' B L2 B' L' B L' B2 L2 B L B' L F",
                "D' R U2 R' U' R U' R' D R' U2 R U R' U R",
                "D R U2 R' U' R U' R' D' R' U2 R U R' U R",
                "R U2 R' U' R U' R' D' R' U2 R U R' U R D",
                "R U2 R' U' R U' R' D R' U2 R U R' U R D'",
                "L F2 R' F' R F' R2 F2 R F R' F R F R L'",
                "R U2 R2 U' R2 U' R2 U2 R F U2 F' U' F U' F'",
                "B' U2 B U B' U B R' U2 R2 U R2 U R2 U2 R'",
                "R' D' R2 U2 R' U' R U' R2 U2 R U R' D U R",
                "R' D R2 U2 R' U' R U' R2 U2 R U R' D' U R",
            ],
            "OsC": [
                "D B2 R D R' B2 D' L U' L B2 U B2 L2",
                "B D' L2 U2 D B' U2 F U2 R2 F R2 U F2",
                "B2 R D R' B2 D' L U' L B2 U B2 L2 D",
                "D B2 R D R' B2 D' L U' L B2 U B2 L2",
                "B U2 B' R2 U' F2 D' F' D F2 U F R2",
                "B D' L2 U2 D B' U2 F U2 R2 F R2 U F2",
                "B L U L2 B2 D' B' D B' L U' B'",
                "B L U L' U B' R B' R' B2 U2 B'",
                "L F U F2 L2 D' L' D L' F U' L'",
                "L F U F' U L' B L' B' L2 U2 L'",
                "B L U L2 B2 D' B' D B' L U' B'",
                "B L U L' U B' R B' R' B2 U2 B'"
            ],
            "OxC": [
                "B' D' F2 D' F' D2 R2 B' D2 F L2 D F2 D B2",
                "F2 L U' L' U2 L R U R' U L F2 L2 U' F2",
                "F2 L U' R U' L' R' U2 L U L F2 L2 U' F2",
                "B' D' F2 U2 D B' L2 F R2 F' L2 D' F2 D B2",
                "B' D' F2 D' F' D2 R2 B' D2 F L2 D F2 D B2",
                "B' R2 D B U2 B U L2 D F' D' L2 B2 D' B",
                "L F' U2 F' R2 D2 B L2 B' D' R D' R F2 L'",
                "R' D L' U L' B2 D U R L2 U2 R' F2 D2 R'",
                "R2 B' D' R2 F U F U' R2 F' D R2 B2 U2 B'",
                "F B2 D2 F' U' R2 B R2 D2 B D2 B' D2 U B2",
                "L F' U2 B' D2 L2 B U2 F' D' R D' R F2 L'",
                "F U' B2 D' R2 D2 B U' B' D2 R2 D B2 U F'",
                "B' D' F2 D U2 B' L2 F R2 F' L2 D' F2 D B2",
                "B' D' F2 D' F' D2 R2 B' D2 F L2 D F2 D B2",
                "F' U' F R' F' R U R U' R' U2 F U2 R U' R'",
                "R U2 R2 U' R2 U' R2 U2 R L' U' L U' L' U2 L",
                "R U R' U' R' U2 B R B' R B R2 B' R U2 R",
                "R D U B' U2 B' U2 B U B' U B U' B D' R'",
                "B L' B2 L U' B U B U' B U B2 L' B2 L B'",
                "F' U' F2 U F R' F2 R U L' U L U2 F U' F'",
                "F U' F U F L F L' U' L F' R' L' F' R F2",
                "F U' F' U' R U2 R2 U' R2 U' R2 U2 R F U' F'",
                "F U F2 U' F2 U' F2 U2 F U' L' U2 B' U' B L",
                "L U L F' D F' D' F L' F U' F U F' U' L'",
                "R U' R2 F R F' R U' R' U2 F' U' F R U R'",
                "L U2 L2 U' L2 U' L2 U2 L F' U2 F U F' U F",
                "B' U2 B U B' U B R U2 R2 U' R2 U' R2 U2 R",
                "F D R2 U' R2 D' F2 U2 F U' F U' F'",
                "F2 U' F' U' R2 B2 D' B R2 F R2 D' B R2",
                "F2 L' U L U L' U' L F2 U2 R U' R'",
                "L F2 R' F' R U' R U R' U F' U' L'",
                "R U2 B' R D' R D R2 B2 U' B' U' R'",
                "R U' R2 F R F' R U' B U' B' U' R'"
            ],
            "CsO": [
                "F U2 F' U B' U2 L2 D' B' D L2 U2 B",
                "B U2 B' L F2 R2 D' F D F' R2 F2 L'",
                "F' D2 B U2 B' D2 F D R2 D' F2 U F2",
                "B U B' U B U2 B' R U2 R' U' R U' R'",
                "B' F' U' F U B U' L2 U' F' U2 F U L2",
                "F' R' U B F U2 F' U F U2 B' F' R F",
                "F' U B' U R2 U F U' F' U' R2 U' B F",
                "B2 U L' R' U' L U R U' B2 U' L' U2 L",
                "B F U2 B' U2 F2 U B U' F2 U' F' U B'",
                "B U R2 U B' F' U' B U F U' R2 U' B'",
                "F' L U2 L' R' U' F U F' L R U2 L' F",
                "B' F' D2 B' D2 B2 U B U' F2 U' F' U B'",
                "B2 L2 B' L2 B' F' U B U' F2 U' F' U B'",
                "L U R' F' R2 U2 F U F' U R2 F L' R",
                "B F2 L2 F U B D' B D B2 U' B' U' F",
                "F' R' U F R B U B' R2 F R F2 R F",
                "B F' U B2 D2 B' D2 B' U' F2 U' F' U B'",
                "F' R B2 L' B' L U' L' U B L B2 R' F",
                "B' D B2 U R U B' U' B R' U' B2 D' B",
                "B F' U' F U B' U2 F2 D' F U2 F' D F2",
                "B' F' U' F U B U2 F2 D F U2 F' D' F2",
            ],
            "CsC": [
                "L U' R' F2 L2 D R' D L' D2 R2 F2 L2",
                "L2 U' F L2 D' L2 D F2 U' F U L2",
                "L2 D' L B2 D' B2 D L2 U' L D L2",
                "L2 U' F L2 D' L2 D F2 U' F U L2",
                "L2 U' F2 D F' U' F2 D' F2 U F' L2",
                "L2 U' F2 D F' D' L2 D' L2 D F' L2",
                "L2 D' L B2 D' B2 D L2 U' L D L2",
                "B2 D B2 U' B L2 U' L2 U B2 D' B",
                "L2 U' F L2 D' L2 D F2 U' F U L2",
                "L2 U' F2 D F' U' F2 D' F2 U F' L2",
                "L2 U' F2 D F' D' L2 D' L2 D F' L2",
                "L2 D' L B2 D' B2 D L2 U' L D L2"
            ],
            "CsA": [
                "F D2 B' U2 B D2 F' D' L2 D F2 U' F2",
                "B D2 F' U2 F D2 B' D' R2 D B2 U' B2",
                "F B U B' U' F' U L2 U B U2 B' U' L2",
                "F' U' L U L' F U L2 D L' U2 L D' L2",
                "B D2 F' U2 F D2 B' D' R2 D B2 U' B2",
                "B R' F2 L2 D F' D' F L2 F2 R B'",
                "L B' R2 F2 D R' D' R F2 R2 B L'",
                "B R' F2 L2 D F' D' F L2 F2 R B'",
                "L U' L' U2 L F' U2 F U F' U F L'"
            ],
            "OsA": [
                "B2 L' D' L B2 D R' U R' B2 U' B2 R2 D'",
                "B' D R2 U2 D' B U2 F' U2 L2 F' L2 U' F2",
                "D' B2 L' D' L B2 D R' U R' B2 U' B2 R2",
                "B2 L' D' L B2 D R' U R' B2 U' B2 R2 D'",
                "B' U2 B L2 U F2 D F D' F2 U' F' L2",
                "B' D R2 U2 D' B U2 F' U2 L2 F' L2 U' F2",
                "B' R' U' R U' B L' B L B2 U2 B",
                "B' R' U' R2 B2 D B D' B R' U B",
                "R' F' U' F U' R B' R B R2 U2 R",
                "R' F' U' F2 R2 D R D' R F' U R",
                "B' R' U' R U' B L' B L B2 U2 B",
                "B' R' U' R2 B2 D B D' B R' U B"
            ],
            "CxO": [
                "F2 U' R' B2 L D2 L' B2 R D R2 B2 U B2 D' R2",
                "F2 D F L2 F' R2 F L2 F' U' B2 U B2 D' R2 F2",
                "F2 D F L2 F' R2 F L2 F' D' R2 U R2 U' R2 F2",
                "F2 D B D2 B' R2 F L2 F' U' B2 U R2 F2 U L2",
                "F2 D B D2 B' R2 F L2 F' D' R2 U F2 L2 D L2",
                "F2 D' F' R2 B D2 B' R2 F U L2 F2 D R2 U' R2",
                "F2 D' F' R2 B D2 B' R2 F D F2 R2 D B2 D' R2",
                "R' U2 R' D B2 D' R U2 R' D B2 D' R2",
                "R' U2 R' D B2 D' R U2 R' D B2 D' R2"
            ],
            "AsC": [
                "L2 U F U2 F' R B L2 B' U' L2 U R'",
                "L U2 L D' B2 D L' U2 L D' B2 D L2",
                "F2 U' F2 U B L2 D' B2 U B2 L2 D B'",
                "L' U2 L U L' U L B' U' B U' B' U2 B",
                "B U B' U' L' U R' U' L F' U2 F U R",
                "F2 L2 B L' F L' F L' B' L U' R U' R'",
                "F L F2 U' R U2 R' U F2 L' F' L U2 L'",
                "L F L' B2 L U2 F' U F U F' U L' B2",
                "L2 F U' F' U B L2 B' U' L2 U2 B' U B",
                "L' U2 R' U F2 L U' L' U F2 U' R U2 L",
                "B2 L U' L' U R2 U2 R2 U B2 D' R D R'",
                "R2 U R U2 L' F D B2 D' F' R L U R'",
                "L' U' F2 L D' U' L' U L D L' F2 U L",
                "D R2 D' F U' F' D R2 D' F' U2 F U2 F",
                "R2 D' F U' F' D R2 D' F' U2 F U2 F D",
                "F' B' U2 R2 F' D' F' D F2 R2 U2 F U B",
                "B2 L U' L' D' F2 D B2 D2 F2 D R D R'",
                "L' F2 R2 B D B' D2 B D B' D R2 F2 L",
                "L' U B2 L2 D' R' U' R D U L2 B2 U' L",
                "D R2 D' F U' F' D R2 D' B' R2 F R2 B",
            ],
            "OsO": [
                "B R2 B R2 U R2 B2 D B2 D' B' R2 B'",
                "B' L2 B' L2 U' L2 B2 D' B2 D B L2 B",
                "L' B2 L2 F R2 F L B2 L' R2 F L' F",
                "R B2 R2 F' L2 F' R' B2 L2 R F' R F'",
                "R B' R B R F R F' R' F R F2 U2 F",
                "L' B L' B' L' F' L' F L F' L' F2 U2 F'",
                "B' U' B U F U2 F2 U B' U' F2 U2 B F'",
                "B U B' U' F' U2 F2 U' B U F2 U2 B' F",
                "R U2 R' U2 B' U F' U' B L' U2 L U F",
                "L' U2 L U2 B U' F U B' R U2 R' U' F'",
                "F U' B D2 B2 D B U B' D' B2 D2 B' F'",
                "F' U B' D2 B2 D' B' U' B D B2 D2 B F",
                "B2 L2 U2 L U R' U' L' U2 L2 U' R U B2",
                "B2 R2 U2 R' U' L U R U2 R2 U L' U' B2",
                "L2 F2 U' B' U F2 U2 F U B U' F' U2 L2",
                "R2 F2 U B U' F2 U2 F' U' B' U F U2 R2",
                "B F2 L B' R2 B2 R' B' L' B R B2 R2 F2",
                "B' F2 R' B L2 B2 L B R B' L' B2 L2 F2",
                "L2 F2 R' F2 L' F R F' L' U2 B L' B' L",
                "R2 F2 L F2 R F' L' F R U2 B' R B R'",
            ],
            "AsO": [
                "B D F2 D F D2 L2 B D2 F' R2 D' F2 D' B2",
                "F2 R' U L' U L R U2 R' U' R' F2 R2 U F2",
                "F2 R' U R U2 L' R' U' L U' R' F2 R2 U F2",
                "B D F2 U2 D' B R2 F' L2 F R2 D F2 D' B2",
                "B D F2 D F D2 L2 B D2 F' R2 D' F2 D' B2",
                "F2 U F U L2 B2 D B' L2 F' L2 D B' L2",
                "F2 R U' R' U' R U R' F2 U2 L' U L",
                "R' L2 D2 R' L' D2 R2 L' U' R U' R' U' L' U L",
                "B' R B' D B' D L D' L D L' D2 B2 R' U' B",
                "F2 R F' U2 F' U2 L' F U' R' F' L' U L U2 L",
                "F U' B' R2 F R2 U' B U F' U' B' U2 F' U' B",
                "F2 B' U2 F2 U F2 L' U L F B U2 L U' L' F",
                "L' U2 L2 U L U' L2 U' R' D' F2 D R2 U' R' L",
                "B L2 F B' U' F' U B L2 B2 U' B U' F' L2 F",
                "F U2 F' U B' U' L2 D' B D L2 B U' B' U B",
                "R' B U2 B' U' R2 U' R' U R2 F D R' D' F' R",
                "L' D B2 D' L U2 R' U' R' F R' U R U' F' R'",
                "R' U' R' F2 R' B' R F R2 B R' F' U2 F2 U R",
                "R' F2 R D F' U' F U' B' R2 B D' U' L' U L",
                "L' U' F' U' B L' D L' D' L2 B2 U F B U L",
                "L' U' F2 U2 L2 F' L' F L' U B' U F2 B U L",
                "R' F' D2 U' R' U F' U' F U' R D2 U F U R",
                "L' U' F U' B L' D L' D' L2 B2 U F' B U L",
                "F2 R F' U' F R' F' D' F' U' L F2 L' F' D F'",
                "R U' R' U2 R' U L D2 L' U' L D F2 D R L'",
                "F' D' L2 U L2 D F2 U2 F' U F' U F",
                "L' U L2 F' L' F L' U B' U B U L",
                "L' U2 B L' D L' D' L2 B2 U B U L",
                "R' F2 L F L' U L' U' L U' F U R"
            ],
            "OxO": [
                "F2 D' F' R2 F L2 F' R2 F U L2 F2 D R2 U' R2",
                "F2 D' F' R2 F L2 F' R2 F D F2 R2 D B2 D' R2",
                "L U2 L D' B2 D L' U2 L' F2 R2 U R2 U' R2 F2",
                "L' B2 L' U F2 U' R D2 R' U R2 B2 D R2 F2",
                "B L2 D2 R F R' D2 F2 L B' L' F2 L2",
                "L F2 D2 B R B' D2 R2 F L' F' R2 F2",
                "B L2 D2 R F R' D2 F2 L B' L' F2 L2",
                "L F2 D2 B R B' D2 R2 F L' F' R2 F2",
                "F U F' U2 L' R' F' U' F U2 L U' R",
                "B L2 D2 R F R' D2 F2 L B' L' F2 L2",
                "F D F2 U' F2 U2 F D U2 B2 U2 F D2 B L2 B",
                "B' U2 B L2 U' R2 D' F D F' R2 U R2 F R2 L2",
                "B' U' B R2 B' D B2 D' R2 U2 R2 D B2 D' B R2",
                "F D B' D U B2 D' U2 B U' R2 U2 B D' R2 F'",
                "R' D2 L2 D F2 D' R L2 U2 R' D2 U L U' R L'",
                "F' U' B D2 B' R2 F' R2 B U F2 U F2 D2 F B'",
                "L D F' U2 L2 D' B' D2 R2 D2 U' B' U2 B2 U' L",
                "B L2 F' B R2 U F U' R2 F2 D B' D' F' B' L2",
                "B L2 F B' L2 D F D' L2 F2 U B' U' F B L2",
                "L' F' L2 B L' F' B' D2 R' B L B2 L' D2 R F2",
                "R' F' U2 B2 L B2 R B2 R' L' B2 U2 F' L' F2 R",
                "L2 D2 R' F' R F' B R2 D2 B' L2 B' L' B L F",
                "F' U' R2 D' F2 U2 F D F' U2 F R2 B U2 F B'",
                "L' U2 R' F2 R U2 L F U2 F2 L' U2 F' U2 L F",
                "R2 L2 B D R' D' R B' D' R2 U' L B2 L' U L2",
                "L B' D2 U2 L B U2 B' L' D2 B2 L' B' R B' R'",
                "L U2 L D' B2 D L' U2 L' F2 R2 U R2 U' R2 F2",
                "F U2 L2 D F D' L2 F2 U B' U F' B L2 F2 L2",
            ]
        },
    },

    // This is for the L ZBLL set
}